### ISSUE TITLE
If parameter starts with number - Causes evaluation to break

### ISSUE THREAD

**Issue by ArisenVendetta** [ncalc/ncalc#101]
Let me start off with thank you for taking it upon yourselves to revive and maintain this library, it is super neat and exactly what I needed when I found it. It was also the only one I could really find for what I needed.

I suppose this could be labelled as a question, or a request/new feature of sorts.
The issue I'm faced with at the moment is if a parameter starts with a number, it will break the evaluation.

I'm using the library to evaluate boolean conditions to determine if, based on the parameters, the condition is true or false.

If I was the source of the parameters, I would just add restrictions when adding parameters to restrict the starting character from being an integer, however the list of parameters that need to be used are coming from externally loaded files which are not created or managed by me, and each one has a specific/unique meaning.

My first thought was to rearrange the characters, so an integer isn't first, but I can't guarantee any sort of rearrangement of the parameter text won't end up causing a collision in the future with a new parameter name, thus I am unable to change the characters around to correct this.

________________________________________________________________________________________________________________

**My question(s):** 
Is this expected behaviour since I have defined the explicit strings as parameters? I would have thought, since they were defined, they would have been treated as variables instead. Although I understand why they wouldn't, since variables don't start with numbers in math.
Is there a way to prevent it from behaving this way?
If there is no way to prevent it, could there be a consideration to add, in the use-case of evaluating purely boolean conditionals, to identify parameters even if they start with a number?
_________________________________________________________________________________________________________________

Code below (can be copy/pasted into a console app) displays my issue.
In the example below, I just explicitly set each parameter to true, but in my end application, the condition being true or not is based on whether its associated checkbox is checked.
```
const string CONDITION = @"(SE_EF)&((3EY00)|(3EH00)|(3DS00))";
try
{
    var parameters = CONDITION.Replace("(", "").Replace(")", "").Split(new char[] { '&', '|' });
    Expression sampleExpression = new Expression(CONDITION);
    foreach (var parameter in parameters)
        sampleExpression.Parameters[parameter] = true;
    Console.WriteLine(sampleExpression.Evaluate());
}
catch (Exception e)
{
    Console.WriteLine(e.ToString());
}
```

**Comment by Bykiev** [comment]
Check the wiki: https://github.com/ncalc/ncalc/wiki/Parameters#square-brackets-parameters

> Parameters in between square brackets can contain special characters like spaces, dots, and also start with digits.

So, with a square brackets you will be able to use parameter names, starting with digit. 

Also, to extract the parameter names you should use `Expression.GetParametersNames()` method
