### ISSUE TITLE
CompareUsingMostPreciseType fails on Int32

### ISSUE THREAD

**Issue by thetreatment** [ncalc/ncalc#102]
If a==null and b.GetType() is Int32, the comparison fails because it is not recognized as a basic type. Only Int64 is included in that set.

**Comment by gumbarros** [comment]
Hey @thetreatment 

PR #116 will solve your problem!

@yallie can you check the PRs and generate a new version? I want to use the new version at Monday :)

**Comment by yallie** [comment]
Hi @gumbarros,

sorry for my late response! Got a bit sick recently...

>can you please check the PRs and generate a new version?

Sure, will do!

**Comment by gumbarros** [comment]
> Hi @gumbarros,
> 
> sorry for my late response! Got a bit sick recently...
> 
> >can you please check the PRs and generate a new version?
> 
> Sure, will do!

No problem, have a good recovery

**Comment by yallie** [comment]
>No problem, have a good recovery

Thank you!
