### ISSUE TITLE
How to get a list of all variables (or their names) used in an expression?

### ISSUE THREAD

**Issue by EnganK** [ncalc/ncalc#103]
Alternatively: is it possible to make it so that if the value of some parameter was not defined, some default value would be used instead of throwing an exception?
Context: I'm using NCalc expressions as part of an in-game programming language, and I need to be sure that even if the user didn't set some variables before evaluating the expression, they'll get a result and not an error.

**Comment by gumbarros** [comment]
Probably you want:

```cs
        var expression= new Expression("42");

        var myVariables = expression.Parameters.Keys;
```

**Comment by EnganK** [comment]
Apparently this doesn't work (which is why I'm asking this question).

```
	var expression = new NCalc.Expression("a + b");
	var myVariables = expression.Parameters.Keys;
	Debug.Log(myVariables.Count);
```
This code outputs 0 when the expected output is 2.

**Comment by gumbarros** [comment]
Probably pull #28 would solve this, I will create another.

**Comment by gumbarros** [comment]
@EnganK my pull request will do the job

**Comment by yallie** [comment]
https://www.nuget.org/packages/NCalcSync/3.11.0
