### ISSUE TITLE
Null handling changed from version 2 to 3

### ISSUE THREAD

**Issue by Coder3333** [ncalc/ncalc#109]
I have this code in my application, and it worked properly with every version of NCalc prior to 3.0.  Now, this same code throws an exception when evaluating the expression.

```c#
            var expression = "{null} = 'WrongValue'";
            var eap = new NCalc.Expression(expression
    // need to indicate NoCache in order to avoid threading issues
    , NCalc.EvaluateOptions.NoCache);

            eap.EvaluateParameter += delegate (string name, NCalc.ParameterArgs args)
            {
                if (name == "null")
                {
                    // if 'null' appears in an expression, it is considered a parameter, so must replace it with
                    // a string.  This will be an issue if comparing "null = 'null'", as it would evaluate to true, instead
                    // of false.  will need to investigate if there is a better way to handle null
                    args.Result = "null";
                }
            };
            var evaluated = eap.Evaluate();
```

Exception:
```
  Message: 
NCalc.EvaluationException : token recognition error at: '{':1:0
token recognition error at: '}':1:5
---- NCalc.EvaluationException : token recognition error at: '{':1:0
token recognition error at: '}':1:5

  Stack Trace: 
Expression.Evaluate()
ExpressionTests.DemonstrateNullException() line 92
----- Inner Stack Trace -----
Expression.Compile(String expression, Boolean nocache)
Expression.HasErrors()

``

**Comment by yallie** [comment]
@Coder3333, you probably used another NCalc fork before. This repository publishes [NCalcSync](https://www.nuget.org/packages/NCalcSync) package.

@gumbarros By the way, NCalc should support square brackets surrounding the parameters.
Comes in handy for parameter names containing spaces and/or unicode characters.

**Comment by Coder3333** [comment]
> @Coder3333, you probably used another NCalc fork before. This repository publishes [NCalcSync](https://www.nuget.org/packages/NCalcSync) package.
> 
> @gumbarros By the way, NCalc should support square brackets surrounding the parameters. Comes in handy for parameter names containing spaces and/or unicode characters.

@yallie , aha.  I have been using https://www.nuget.org/packages/CoreCLR-NCalc/.  Didn't realize I had the wrong repo.  Any idea if I should be able to switch to this package without too much work?

**Comment by yallie** [comment]
>I have been using [nuget.org/packages/CoreCLR-NCalc](https://www.nuget.org/packages/CoreCLR-NCalc/). Didn't realize I had the wrong repo. Any idea if I should be able to switch to this package without too much work?

@Coder3333, not sure why would you? 
CoreCLR-NCalc seems to be doing just fine. Updated 10 days ago, 4.2M downloads 👍
I haven't used it myself and don't know how it compares to NCalcSync, sorry...

**Comment by yallie** [comment]
>@yallie yeah, but don't support curly braces "{" right? I use these because of old and large legacy systems without NCalc that were using DataTable.Compute.

@gumbarros  Oh, I see. You're right, NCalc doesn't support curly braces.
