### ISSUE TITLE
EvaluateOptions.IgnoreCase is not working in .net framework 4.6 version

### ISSUE THREAD

**Issue by ptitera** [ncalc/ncalc#110]
.net framework 4.6 version ignores EvaluateOptions.IgnoreCase option. I think primary constructors as used in code are not supported in this framework.

**Comment by ptitera** [comment]
My expression is: IN([acp_associated_person_transactions], 'T', 'Z', 'A')

My Expression object is created like this:

```
            var expression = new NCalc.Expression(expressionStr) {
                Options = EvaluateOptions.RoundAwayFromZero | EvaluateOptions.IgnoreCase,
            };
```
So it should ignore casing error. But I get this exception:

```
System.ArgumentException: Function not found IN. Try in instead.
   at NCalc.Domain.EvaluationVisitor.CheckCase(String function, String called)
   at NCalc.Domain.EvaluationVisitor.Visit(Function function)
   at NCalc.Expression.Evaluate()
```

When I look at object state in debugger I see that Optins of `Expression` are set correctly but `IgnoreCase` property of `EvaluationVisitor` is false.

Concerning primary constructors. Are you sure they are only syntax sugar? This article https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors uses .NET 8 as prerequisity. But I may be wrong.

**Comment by gumbarros** [comment]
.NET 8 is a prerequisite because it comes with C# 12 enabled by default. You can target .NET 4.8 and use primary constructors with `<LangVersion>12</LangVersion>` at .csproj (NCalc do this for example).

Nice that is working, can you share the complete snippet of the EvaluationVisitor problem?

**Comment by gumbarros** [comment]
![image](https://github.com/ncalc/ncalc/assets/52143624/b56db39b-93d4-4844-875c-37469fdd7068)

Ok reproduced.

**Comment by ptitera** [comment]
More I look at current code more I think it is subtly broken. How are `EvaluateFunction` and `EvaluateParameter` events set when `EvaluationVisitor` is instantiated in constructor?

**Comment by gumbarros** [comment]
> Author

Yes, I'm using the same solution to set `Options `at `EvaluationVistor`
https://github.com/ncalc/ncalc/pull/111
