### ISSUE TITLE
Allow using decimals as default for floating points

### ISSUE THREAD

**Issue by lucaschimweg** [ncalc/ncalc#117]
Hey,

for a use-case I'm working on it would be very helpful to allow specifying the default type for floating point numbers as `decimal` instead of `double`. When specifying this setting, floating point rounding errors can be avoided in many cases, at the cost of performance. Since decimals are already supported the changes within the code base should not be too large from my first investigation. 

Is this a feature that would be of interest for merging? I'll happily prepare a PR for this.

**Comment by niikoo** [comment]
Thank you for adding support for `decimal`.
Hope that one of the maintainers will review your PR soon.

**Comment by gumbarros** [comment]
@yallie
