### ISSUE TITLE
Unit tests fails with locale other than English

### ISSUE THREAD

**Issue by axunonb** [ncalc/ncalc#120]
This unit test fails on systems where the locale is other than English:
https://github.com/ncalc/ncalc/blob/08994e2c366d4f2621aeea461c0e12ac1448dbf4/test/NCalc.Tests/Fixtures.cs#L712
The cause is here:
https://github.com/ncalc/ncalc/blob/08994e2c366d4f2621aeea461c0e12ac1448dbf4/src/NCalc/Expression.cs#L205-L232
I think it would be better to throw a new `EvaluationException` using the overload `EvaluationException(string message, Exception innerException)` to add the original exception as inner exception. In the unit test, the inner exception could identify the cause with `DeclaringType == typeof(System.DateTimeParse)` rather than testing for the message.
Would you accept a PR for that?

Btw.: `publish-nuget.yml` should update the depreciated `actions/checkout@v2` with `actions/checkout@v4`.

**Comment by gumbarros** [comment]
@axunonb sorry for the late reply, you can make a PR with the changes if you want. I will review and merge :)
