### ISSUE TITLE
Floating point numbers have wrong evaluation type

### ISSUE THREAD

**Issue by lexalambada** [ncalc/ncalc#121]
Hello, everyone.

Maybe I've understood something wrong, but in documentation we have statement, that floating point numbers are evaluated as **Decimal**. 
![image](https://github.com/ncalc/ncalc/assets/122774415/481f8bc2-2ae4-4f1c-a09b-5cc22a4bc6d7)

I had expectation that the result of adding two "decimal" numbers should also be "decimal". But the result type is **Double**.
Did I understand something wrong or this is a bug?)

![image](https://github.com/ncalc/ncalc/assets/122774415/e414a363-1649-4021-828f-836027b0f7aa)

**Comment by gumbarros** [comment]
I think this is related to #117, try using `EvaluateOptions.DecimalAsDefault`

**Comment by lexalambada** [comment]
@gumbarros Thanks a lot. I've updated to the latest NCalc version. Now I have**EvaluateOptions.DecimalAsDefault** and the result has expected **decimal** type. 

I have one more question. Probably you could help me again:) 
The question is about result types of built in math functions. For example **Exp()** has result type **Double**
![image](https://github.com/ncalc/ncalc/assets/122774415/76fb8363-daf9-4496-b7fc-74e15db3892b)

Is there any way to switch built in Math functions to decimal type?

**Comment by gumbarros** [comment]
Yw! Just updated the docs to avoid confusion.

About Exp(), I think I will need to fix this.

**Comment by lexalambada** [comment]
Thanks for your quick replies.
It would be greate to have an option to switch all Math functions to decimal.
I'll be looking forward to this functionality. 
Maybe you have some expectations, when will you try to fix this?

**Comment by gumbarros** [comment]
> Thanks for your quick replies. It would be greate to have an option to switch all Math functions to decimal. I'll be looking forward to this functionality. Maybe you have some expectations, when will you try to fix this?

Developing right now a solution :)

**Comment by gumbarros** [comment]
Update: This is expected behavior, `Math.Exp` returns a `double`.

https://learn.microsoft.com/en-us/dotnet/api/system.math.exp?view=net-8.0

**Comment by lexalambada** [comment]
> Update: This is expected behavior, `Math.Exp` returns a `double`.
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.math.exp?view=net-8.0
> 
> If you really really want to return a `decimal` from an Exp() function, you can create your own `ExpAsDecimal` function and use `OnEvaluateFunction`

Thank you. You help me a lot :)
