### ISSUE TITLE
How to get the inverse function

### ISSUE THREAD

**Issue by siyuanAUV** [ncalc/ncalc#125]
Hi,
How to get the inverse function? 
The Expression:
"y=x*5+10"

i just want get the function: "x=(y-10)/5"

do we support?

**Comment by gumbarros** [comment]
No, this is not a supported scenario. You would need to manually calculate the inverse function. I'm not sure, but if a inverse functino is x and y inverted, maybe you can invert the parameters at `Parameters` property, but again, not a officially supported scenario.
