### ISSUE TITLE
`SerializationVisitor` Erroneously Serializes `BitwiseXOr` as `~`

### ISSUE THREAD

**Issue by jim-noble-milliman** [ncalc/ncalc#133]
The `LogicalExpression` type's `ToString()` method uses the `SerializationVisitor` type to construct the string representation of the expression tree. Unfortuntely, there is a defect in the code in `SerializationVisitor.cs`, line 98:

```cs
case BinaryExpressionType.BitwiseXOr:
    Result.Append("~ ");
    break;
```

The symbol for `BitwiseXOr` is `^`, but the serializer method returns `~`. Apparently this was confused with the unary `BitwiseNot` operator.

As a result, a `LogicalExpression` parsed from e.g. `1 ^ 2` will return `1 ~ 2` from `.ToString()`. And since this is not syntactically valid, trying to compile that resulting expression throws an expectable parsing error.

The good news is this is a super easy fix, the `~` just needs to be replaced with a `^` on that line of code.

**Comment by gumbarros** [comment]
Good night @jim-noble-milliman !

I made the fix at #134, thanks for the issue. The expected result is 3 right?

**Comment by jim-noble-milliman** [comment]
Yes, I think that would be the expected output. But I am not sure your unit test demonstrates the exact issue at hand here, as there is not (I think) a call to the `SerializationVisitor` in the loop. A verifying test might be something like:
```cs
var logicalExpression = Expression.Compile(expression: "1 ^ 2", nocache: false);

var serializedString = logicalExpression.ToString();

Assert.Equal("1 ^ 2", serializedString);
```
In any case, thanks for the amazing turn around time. Is there a way I can track the fix to a nuget release version?

**Comment by gumbarros** [comment]
Good morning @jim-noble-milliman !

Updated the test and everything working. I will wait a review and maybe today we can release a 3.13.1
