### ISSUE TITLE
Replace ANTLR with a modern parser

### ISSUE THREAD

**Issue by sebastienros** [ncalc/ncalc#137]
ANTLR is awesome, but it's slower and less flexible than newer parsers. I would suggest to use something like [Parlot](https://github.com/sebastienros/parlot) (because I wrote it and it's the best 😅) or [Irony](https://github.com/IronyProject/Irony) because I have used it by the past and @yallie is a maintainer who also uses NCalc.

That would also make the grammar more extensible and people might be able to reconfigure it to some extent.

If people are interested in this effort (an Parlot) I think it would be valuable to do it in a live/recorded meeting (skype/teams/YT). That would teach how the parser is used in NCalc and how Parlot works.

And finally run a benchmark to show the improvements, if any... or throw it away

**Comment by gumbarros** [comment]
Interessing challenge. Looks awesome for a v2 :)

Not very familiar with language parsers, awesome opportunity to learn.

**Comment by sebastienros** [comment]
Already managed to get something working, generates the same AST, that is 3 times faster when evaluating these in a loop without caching:

```c#
            var expressions = new[]
            {
                "[age] = 18",
                "2 * (3 + 5)",
                "2 * (2*(2*(2+1)))",
                "10 % 3",
                "false || not (false and true)",
                "3 > 2 and 1 <= (3-2)",
                "3 % 2 != 10 % 3",
                "Sin(3.14)",
                "'A' = 'A' ? 10 : ('B' = 'B' ? 15 : 20)",
                "if ('A' = 'A', 10, if ('B' = 'B', 15, 20))",
                "if ( [age] >= 18, 'majeur', 'mineur')",
                //"CalculateBenefits([user]) * [Taxes]"
            };
```

This is what would replace the grammar+lexer+parser.

https://gist.github.com/sebastienros/20da468604e8abab6e34cb094571cd53

Usage:

```c#
var parser = NCalcParser2.Expression;
parser.TryParse(expression, out logicalExpression, out var error);
```

**Comment by gumbarros** [comment]
:o, I was just studying your lib and you did this. Soon I will probably open a issue regarding generics at Parlot, that can probably solve #128 for example.

![image](https://github.com/ncalc/ncalc/assets/52143624/4e2c9801-eae3-4643-9109-4ba81b28abff)

Just some unit tests to check, I will open a branch so you can see.

**Comment by gumbarros** [comment]
You can check https://github.com/ncalc/ncalc/tree/parlot-experiment

**Comment by gumbarros** [comment]
At this exact moment I'm trying to re write the Unit Test of Parlot to use Generic Math (https://github.com/sebastienros/parlot/issues/101)

If it works, it would be probably a similar logic for NCalc at differing numeric types. 

Counterpoint: It will not work in older target runtimes.

**Comment by sebastienros** [comment]
Trying to fix units tests one by one at that point is a good strategy. Let me know when you are blocked. the easy next steps would be to add bitwise, exponentiation operators. Supporting decimal vs double could also be done by exposing the specific parser for this option publicly no the class. Or instead of using a static parser, have a method to create it that would have parsing options (then cache the result).

I looked a the source code again (so long I didn't remember how it worked) and have made better designs to handle conversion and operations between types. Maybe it's not possible to change it because the behaviors would be different, but in Fluid for instance this is quite simpler, there is a base `FluidValue` type and operations to convert to the different base types. Then an operation is calling `ToNumber()` on these for instance: https://github.com/sebastienros/fluid/blob/main/Fluid/Filters/NumberFilters.cs#L50

Maybe something to look into instead of have all these switch/case for each type combination. In a later step.

**Comment by Bykiev** [comment]
Parlot seems very promising, would like to see BenchmarkDotNet vs ANTLR tests

**Comment by Bykiev** [comment]
I did some tests and seems Parlot is really super fast. Test case: `1 - ( 3 + 2.5 ) * 4 - 1 / 2 + 1 - ( 3 + 2.5 ) * 4 - 1 / 2 + 1 - ( 3 + 2.5 ) * 4 - 1 / 2`

BenchmarkDotNet v0.13.12, Windows 10 (10.0.19045.4291/22H2/2022Update)
Intel Core i3-6100U CPU 2.30GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET SDK 8.0.204
  [Host] : .NET 6.0.29 (6.0.2924.17105), X64 RyuJIT AVX2

Toolchain=InProcessNoEmitToolchain  IterationCount=3  LaunchCount=1
WarmupCount=3

| Method                | Job     | NuGetReferences       |Mean     | Error    | StdDev   |
|---------------------- |-------- |---------------------- |---------:|---------:|---------:|
| TestFormulaEvaluation | 3.1.244 | CoreCLR-NCalc 3.1.244 | 83.80 us | 41.32 us | 2.265 us |
| TestFormulaEvaluation | 3.13.0  | NCalcSync 3.13.0      | 76.55 us | 32.69 us | 1.792 us |  0.91 |
| ParlotRawBig        |  ||3,171.8 ns |  2,860.2 ns |   156.78 ns |  0.53 |    0.02

**Comment by gumbarros** [comment]
> Trying to fix units tests one by one at that point is a good strategy. Let me know when you are blocked. the easy next steps would be to add bitwise, exponentiation operators. Supporting decimal vs double could also be done by exposing the specific parser for this option publicly no the class. Or instead of using a static parser, have a method to create it that would have parsing options (then cache the result).
> 
> I looked a the source code again (so long I didn't remember how it worked) and have made better designs to handle conversion and operations between types. Maybe it's not possible to change it because the behaviors would be different, but in Fluid for instance this is quite simpler, there is a base `FluidValue` type and operations to convert to the different base types. Then an operation is calling `ToNumber()` on these for instance: https://github.com/sebastienros/fluid/blob/main/Fluid/Filters/NumberFilters.cs#L50
> 
> Maybe something to look into instead of have all these switch/case for each type combination. In a later step.

This probably will work fine

```cs
        var number = OneOf(
            Terms.Decimal().Then<LogicalExpression>(static d => new ValueExpression(d)),
            Terms.Double().Then<LogicalExpression>(static d => new ValueExpression(d)),
            Terms.Integer().Then<LogicalExpression>(static d => new ValueExpression(d))
        );
```

**Comment by sebastienros** [comment]
Yes, that works. But my comment was not about the switch/cases in the parlot grammar (in case you referred to it) but the ones in ncalc which handle the casting when an operation is invoked between two values like `1 + 2.3` where ncalc says "it's a double on the right, so we need to cast the left integer".

**Comment by gumbarros** [comment]
> Yes, that works. But my comment was not about the switch/cases in the parlot grammar (in case you referred to it) but the ones in ncalc which handle the casting when an operation is invoked between two values like `1 + 2.3` where ncalc says "it's a double on the right, so we need to cast the left integer".

Yeah, I was talking about generics for parsing not interpreting. For interpreting, NCalc already have everything done with `ValueExpression` and `Numbers.cs`, but maybe, Generic Math works better in a far future.

**Comment by Bykiev** [comment]
> > Trying to fix units tests one by one at that point is a good strategy. Let me know when you are blocked. the easy next steps would be to add bitwise, exponentiation operators. Supporting decimal vs double could also be done by exposing the specific parser for this option publicly no the class. Or instead of using a static parser, have a method to create it that would have parsing options (then cache the result).
> > I looked a the source code again (so long I didn't remember how it worked) and have made better designs to handle conversion and operations between types. Maybe it's not possible to change it because the behaviors would be different, but in Fluid for instance this is quite simpler, there is a base `FluidValue` type and operations to convert to the different base types. Then an operation is calling `ToNumber()` on these for instance: https://github.com/sebastienros/fluid/blob/main/Fluid/Filters/NumberFilters.cs#L50
> > Maybe something to look into instead of have all these switch/case for each type combination. In a later step.
> 
> This probably will work fine
> 
> ```cs
>         var number = OneOf(
>             Terms.Decimal().Then<LogicalExpression>(static d => new ValueExpression(d)),
>             Terms.Double().Then<LogicalExpression>(static d => new ValueExpression(d)),
>             Terms.Integer().Then<LogicalExpression>(static d => new ValueExpression(d))
>         );
> ```

The better way will be 

```
  number = OneOf(
      Terms.Integer(NumberOptions.AllowSign)
      .AndSkip(Terms.Char('.'))
      .And(Terms.Integer())
      .Then<LogicalExpression>(x =>
          new ValueExpression(options.UseDecimalsAsDefault ?
          Convert.ToDecimal(x.Item1 + "." + x.Item2, CultureInfo.InvariantCulture) :
          Convert.ToDouble(x.Item1 + "." + x.Item2, CultureInfo.InvariantCulture))),
          intParser
  );
```

**Comment by gumbarros** [comment]
> > > Trying to fix units tests one by one at that point is a good strategy. Let me know when you are blocked. the easy next steps would be to add bitwise, exponentiation operators. Supporting decimal vs double could also be done by exposing the specific parser for this option publicly no the class. Or instead of using a static parser, have a method to create it that would have parsing options (then cache the result).
> > > I looked a the source code again (so long I didn't remember how it worked) and have made better designs to handle conversion and operations between types. Maybe it's not possible to change it because the behaviors would be different, but in Fluid for instance this is quite simpler, there is a base `FluidValue` type and operations to convert to the different base types. Then an operation is calling `ToNumber()` on these for instance: https://github.com/sebastienros/fluid/blob/main/Fluid/Filters/NumberFilters.cs#L50
> > > Maybe something to look into instead of have all these switch/case for each type combination. In a later step.
> > 
> > 
> > This probably will work fine
> > ```cs
> >         var number = OneOf(
> >             Terms.Decimal().Then<LogicalExpression>(static d => new ValueExpression(d)),
> >             Terms.Double().Then<LogicalExpression>(static d => new ValueExpression(d)),
> >             Terms.Integer().Then<LogicalExpression>(static d => new ValueExpression(d))
> >         );
> > ```
> 
> The better way will be
> 
> ```
>   number = OneOf(
>       Terms.Integer(NumberOptions.AllowSign)
>       .AndSkip(Terms.Char('.'))
>       .And(Terms.Integer())
>       .Then<LogicalExpression>(x =>
>           new ValueExpression(options.UseDecimalsAsDefault ?
>           Convert.ToDecimal(x.Item1 + "." + x.Item2, CultureInfo.InvariantCulture) :
>           Convert.ToDouble(x.Item1 + "." + x.Item2, CultureInfo.InvariantCulture))),
>           intParser
>   );
> ```

Nice, this sure looks better and will probably fix many tests, I will make the change tonightor you can commit at `parlot-experiment` if you want.

**Comment by sebastienros** [comment]
The options should be passed in a custom `ParserContext` class IMO. The context is what is given to each evaluation, that could become handy if the same app needs two different values. `Then` has an overload that can provide the `ParserContext`, which can then be casted to the actual implementation to get the custom property Options.

**Comment by gumbarros** [comment]
> The options should be passed in a custom `ParserContext` class IMO. The context is what is given to each evaluation, that could become handy if the same app needs two different values. `Then` has an overload that can provide the `ParserContext`, which can then be casted to the actual implementation to get the custom property Options.

Yes, I was thinking it was wrong to don't use a static class for the Parser and was looking for some Context class. Can you share when possible a small snippet here or from Parlot repo in how to pass a `ParserContext`

**Comment by sebastienros** [comment]
Custom ParseContext class with custom properties: 
https://github.com/sebastienros/fluid/blob/bbb64b35b29345076244d131b760f9af1e3ac837/Fluid/Parser/FluidParseContext.cs#L17

Usage example in the grammar:
https://github.com/sebastienros/fluid/blob/bbb64b35b29345076244d131b760f9af1e3ac837/Fluid/FluidParser.cs#L403

How to create one when calling `Parse`:
https://github.com/sebastienros/fluid/blob/bbb64b35b29345076244d131b760f9af1e3ac837/Fluid/FluidParserExtensions.cs#L15-L17
