### ISSUE TITLE
 Obtaining a List of Parameters in a Generic Expression Before Function Evaluation

### ISSUE THREAD

**Issue by Beckdotan** [ncalc/ncalc#141]
Hello, I'm curious if there's a built-in method to retrieve a list of all parameters within an expression prior to its evaluation using Expression.Compile(expression).

Expressions might appear as follows:
if(DP(3)!=0, DP(43)+Q(58)/(1000*DP(3)), null)

My goal is to obtain a list like [DP(43), Q(58), DP(3), null], allowing me to iterate through it and assign values to each parameter based on my own logic.

**Comment by gumbarros** [comment]
Yes, exactly. There is not doc because is a recent feature from months ago. But the behavior is 100% what you described.

**Comment by Beckdotan** [comment]
@gumbarros  Thank you for your help! Unfortunately, I'm still experiencing issues. From what I understand, the functionality should be available in version 3.11 and later, right?

Here’s the code I’m working with: [https://dotnetfiddle.net/5iSl8A](url)

I’m encountering a compilation error at line 66, column 26: 'NCalc.Domain.LogicalExpression' does not contain a definition for 'GetParametersNames', and no accessible extension method 'GetParametersNames' can be found for the type 'NCalc.Domain.LogicalExpression' (possibly missing a using directive or an assembly reference?).

The error arises when evaluating the expression "X + 5". I'm puzzled as to why it returns a 'LogicalExpression' rather than a 'BinaryExpressionType', and why the 'GetParametersNames' function is missing.

**Comment by gumbarros** [comment]
You need to pass your `LogicalExpression` object to an `Expression` object, the `GetParameterNames` is in this class.

https://github.com/ncalc/ncalc/blob/36ab031d19a6e560d0cb599f76d2a12f775b5767/src/NCalc/Expression.cs#L347

**Comment by gumbarros** [comment]
Hi @Beckdotan !

Sorry for the late response, I was pretty busy working on v4. 

I fixed your problem at this commit https://github.com/ncalc/ncalc/pull/142/commits/9593a93f60b4d97f336e1a8cb4050319050305c3.

v4 will probably arrive tomorrow

**Comment by Beckdotan** [comment]
@gumbarros  Thanks so much. So will it be up with the V4? 

Thanks again! 2

**Comment by gumbarros** [comment]
> @gumbarros  Thanks so much. So will it be up with the V4? 
> 
> Thanks again! 2
> 

Yes
