### ISSUE TITLE
double.NaN <= 15.95  returns true

### ISSUE THREAD

**Issue by canyoneer123** [ncalc/ncalc#145]
A curious case occurs when trying to compare doubles to NaNs. In my experience, (NaN <= anything) is a false statement. However, I can get it to produce a true result here in some cases like below.

````
var test = new Expression("myValue <= 15.95");
test.Parameters["myValue"] = double.NaN;
var result = test.Evaluate(); // returns true, which is unexpected

var test = new Expression("myValue >= 15.95");
test.Parameters["myValue"] = double.NaN;
var result = test.Evaluate(); // returns false
````

**Comment by canyoneer123** [comment]
It looks like this is a 'feature' of the  System.Collections.Comparer.Default.Compare(double.NaN, x).

It also has the same 'feature' if you replace NaN with null, which also seems unusual. However, I can acknowledge that even if it doesn't produce the same behavior as `double.Nan <= 15.95`, it is at least standard behavior in the sense that it's the Comparer.Default's behavior.

**Comment by gumbarros** [comment]
@canyoneer123 thanks for the initial debug. As this is the default `Comparer.Default` behavior, **I think**, we cannot modify it, but you can create your own with your own `Expression` class by setting a custom `EvaluationVisitor`
