### ISSUE TITLE
Regression when updating to v4. - Invalid tokens are silently ignored

### ISSUE THREAD

**Issue by dkonovalov** [ncalc/ncalc#150]
**Describe the bug**
When expression with invalid token was evaluated in version 3.12 , error was returned. In v4 it returns the value without error. 

**Example Expression**
-42a

Expected result: exception
Actual result: -42

In this example, there is no parameter called "a" defined etc, it's just an arbitrary symbol.

**Comment by gumbarros** [comment]
Hi @dkonovalov, thanks for the report and sorry for the inconvenience. The behavior changed because we are not using Antlr anymore.

Tonight I will create a unit test with your expression and develop a fix.
