### ISSUE TITLE
Support function effects outside of expression

### ISSUE THREAD

**Issue by slobber** [ncalc/ncalc#151]
I want create a function to check a value whether large than 10 three times. 

The Expression will be `Repeat([value] > 10, 3)`.

```
 var e = new Expression("Repeat([value] > 10, 3)");
 
 var times = new Dictionary<string, int>() { };

 e.EvaluateFunction += (name, args, id) =>
 {
     if (name == "Repeat")
     {
         var t = (int)args.Parameters[1].Evaluate() - 1;
         var r = (bool)args.Parameters[0].Evaluate();
         if (r && id != null)
         {
             if (!times.ContainsKey(id))
             {
                 times[id] = t;
             }
             else
             {
                 times[id]--;
             }
         }

         args.Result =  r && times[id] == 0;
     }
 };
 e.Parameters["value"] = 9;

 Assert.Equal(false, e.Evaluate());
 
 e.Parameters["value"] = 11;
 Assert.Equal(false, e.Evaluate());
 e.Parameters["value"] = 12;
 Assert.Equal(false, e.Evaluate()); 
 e.Parameters["value"] = 13;
 Assert.Equal(true, e.Evaluate()); 
```

**Comment by gmcchessney** [comment]
We had a similar requirement (maintaining state within a unique function instance) and got around the limitation by pre-processing the expression. In our use-case we modified the function names to be unique, but you could also inject an "id" parameter into the functions. Here's an example repo with parameter injection, just take a look in NCalc.Play:

https://github.com/gmcchessney/ncalc/tree/unique-function-id-workaround-151
