### ISSUE TITLE
Add support for comparison of values to null

### ISSUE THREAD

**Issue by Bykiev** [ncalc/ncalc#153]
Hi, I'd like to discuss implementing comparison of values to null. In this fork https://github.com/sklose/NCalc2/ there is `EvaluateOptions.AllowNullParameter` option, we're actively using it. Would like to port this feature to NCalc.

**Comment by gumbarros** [comment]
Compilation to lambda is also a nice idea to borrow

**Comment by Bykiev** [comment]
I'd say it's better to port fork to Parlot too. Lambda compilation is the key difference between them and I think they should go own way

**Comment by Beckdotan** [comment]
I wanted to suggest. 
[Here is a document]( https://docs.google.com/document/d/1dhJF1N8w6UD0p7EJFsjCUdkTkMJUp3xpt0I7YM-Q7as/edit?usp=sharing)
describing the logic of dealing with null values I have developed with my own visitor and suggest using it in the system. 
There is also a link to my implementation of this logic. 

I hope it make sense to you.

**Comment by Bykiev** [comment]
> I wanted to suggest. [Here is a document](https://docs.google.com/document/d/1dhJF1N8w6UD0p7EJFsjCUdkTkMJUp3xpt0I7YM-Q7as/edit?usp=sharing) describing the logic of dealing with null values I have developed with my own visitor and suggest using it in the system. There is also a link to my implementation of this logic.
> 
> I hope it make sense to you.

Unfortunately, there is no access to this file
