### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#154]
**Is your feature request related to a problem? Please describe.**
I want use `IMemoryCache` at the cache, but don't want to create a dependency in NCalc with this.

**Describe the solution you'd like**
Create a `NCalc.DependencyInjection` package with a dependency on `Microsoft.Extensions.DependencyInjection`

At `Program.cs`:
```
builder.Services.AddNCalc()
.WithCache<CustomCacheImplementation>()
.WithParser<CustomParser>
.WithEvaluationVisitor<CustomEvaluationVisitor>();

builder.Services.AddTransient<MyService>():
```

Usage:
```
using NCalc;

namespace JJMasterData.NCalc;

public class MyService(IExpressionFactory expressionFactory)
{
  
    public object? Evaluate(string expression)
    {
        var expression = expressionFactory.Create(replacedExpression);
 
        return expression.Evaluate();
    }
 
}
```

**Describe alternatives you've considered**
Inheriting `Expression`, but feels over-engineering, I don't like currently on how we create custom `EvaluationVisitor`s.

**Additional context**
My team on JJMasterData also want to use `{}` as identifier, we currently pre-parse the expression to find these identifiers, a `ILogicalExpressionParser` would solve the problem.

**Comment by Bykiev** [comment]
I like this idea, we've discussed it in another fork https://github.com/sklose/NCalc2/issues/101, but ended up limiting the frequency of cleaning the expression cache by `CacheCleanInterval` parameter

**Comment by gumbarros** [comment]
Another good point, if a user wants to rollback to ANTLR or another parser, it will be possible with a `ILogicalExpressionParser `interface.
