### ISSUE TITLE
Abs(x)/Pow(y,2) crashes

### ISSUE THREAD

**Issue by steda638** [ncalc/ncalc#16]
The error raised is: Operator '/' cannot be applied to operands of type 'decimal' and 'double'. It appears that Abs() is returning a Decimal even though x was a Double.

**Comment by ntimmerman** [comment]
Ran into this problem too.

I'm sure its wrong but I worked around it for now with: 

```
var calcExpression = new Expression(formula);
                var usedInputData = new Dictionary<string, double?>();
                
                var result = formula.Contains("Abs") ? decimal.ToDouble((decimal)calcExpression.Evaluate()) : (double)calcExpression.Evaluate();
```

**Comment by steda638** [comment]
Thank you. I worked around it in a different way by using either Round(Abs(x),4)/Pow(y,2) or Abs(x)/Abs(Pow(y,2)).
