### ISSUE TITLE
Discussion: Should plugins be in a separated repo or inside this repo in Plugins folder?

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#165]
PR #160 adds a `IMemoryCache` plugin. This should be in the same repo or a separated repo?

We can also create for example create a `NCalc.Antlr` plugin by just implementing `ILogicalExpressionFactory` and calling `WithLogicalExpressionFactory` at `Program.cs` (docs for DI incoming tomorrow). 

Should plugins be in a separated repo? I particurally prefer everything in the same repo to prevent breaking changes [like here for example](https://github.com/JJConsulting/JJMasterData/tree/main/src/Plugins). But I would like to have some community input.

**Comment by Bykiev** [comment]
I prefer a monorepo, it will simplify development and dependency management. NCalc is not a big project with hundred of maintainers, so, all the issues of monorepo are has low impact.
