### ISSUE TITLE
Do not convert external function name to lower case if ignoreCase is specified

### ISSUE THREAD

**Issue by Bykiev** [ncalc/ncalc#168]
Right now when the external function is called and `ignoreCase` is used the function name is converted to lower case. I think we shouldn't convert it to any case and pass the original name to external. In most cases `ToUpperInvariant()` should be used in external implementation (the same as for built-in functions). It'll be a breaking change again, so, need to be discussed.

https://github.com/ncalc/ncalc/blob/abd34129c13b04a76a308e7127d95253c5844908/src/NCalc/Visitors/EvaluationVisitor.cs#L286

**Comment by gumbarros** [comment]
100% agree, I event added a warning at my docs because of this weird behavior

![image](https://github.com/ncalc/ncalc/assets/52143624/ebbbe030-8579-433b-a11c-ff00329e8821)
