### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by jferrazza** [ncalc/ncalc#17]
Is there a way to make it detect divide by zero and integer overflow? 2/0 returns infinity and multiplying large numbers returns a negative number.

I remember this is to do with using the wrong object type.

**Comment by se5a** [comment]
Ohhhhh, is *THIS* what I'm seeing in https://github.com/ncalc/ncalc/issues/39

**Comment by Bykiev** [comment]
This is supported now with `ExpressionOptions.OverflowProtection`
