### ISSUE TITLE
NCalcAsync should be merged at this repo.

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#172]
Probably a v5 milestone. 

[ncalc-async](https://github.com/ncalc/ncalc-async) is 6 months behind, and every new feat or fix needs to be manually added to the other repo. 

The best way to solve this problem would be:

```mermaid
graph TD;
    NCalcSync-->NCalc;
    NCalcAsync--> NCalc;
```

**Comment by gumbarros** [comment]
Also a design flaw (I think)

Only `EvaluationVisitor` should be async and probably 80% of the codebase can be re-used. Because all code runs sync and just return `Task.CompletedTask`. The big advantage of NCalcAsync is to do CPU/IO bound work inside event handlers of `IEvaluationVisitor`.

**Comment by gumbarros** [comment]
```cs

public interface IEvaluationVisitorContract : ILogicalExpressionVisitor
{
    public event EvaluateFunctionHandler? EvaluateFunction;
    public event EvaluateParameterHandler? EvaluateParameter;
    
    ExpressionContext Context { get; set; }
    
    public Dictionary<string, object?> Parameters { get; set; }
}
public interface IEvaluationVisitor : IEvaluationVisitorContract
{    
    public object? Result { get; }
}

public interface IAsyncEvaluationVisitor : IEvaluationVisitorContract
{
    public Task? Result { get; }
}
```

This would solve all the problems in theory.

**Comment by gumbarros** [comment]
Also, if this works (looks very promising for me), we can in theory have a single Assembly with both sync and async, but idk what everyone thinks on this, and the name NCalc is already taken.

**Comment by ThomasHambach** [comment]
Thumbs up on my end. That would definitely streamline the work we have to put into merging the features/fixes! I think keeping the package name as is would be fine as in the codebase you are already referring to `Ncalc` and not `NcalcSync`. We just need to add the proper info on the `NcalcAsync` package.

**Comment by gumbarros** [comment]
> me), we can in theory have a single Assembly with both sync and async, but idk what everyone thinks on this, and the name NCalc is already taken.

I think we can just work with:

NCalc -> Assembly not published to NuGet, (but if someone wants we can), with all shared business logic.
NCalcSync -> Assembly with `Expression` and `EvaluationVisitor`
NCalcAsync -> Assembly with `AsyncExpression` and `AsyncEvaluationVisitor`

**Comment by ThomasHambach** [comment]
> > me), we can in theory have a single Assembly with both sync and async, but idk what everyone thinks on this, and the name NCalc is already taken.
> 
> I think we can just work with:
> 
> NCalc -> Assembly not published to NuGet, (but if someone wants we can), with all shared business logic. NCalcSync -> Assembly with `Expression` and `EvaluationVisitor` NCalcAsync -> Assembly with `AsyncExpression` and `AsyncEvaluationVisitor`

As much as I like the approach of making things more clear, I don't like the usability aspect of it and feels like it leans towards the nodejs package hell. I'd personally prefer keeping things in the same package as much as possible.

**Comment by gumbarros** [comment]
> > > me), we can in theory have a single Assembly with both sync and async, but idk what everyone thinks on this, and the name NCalc is already taken.
> > 
> > 
> > I think we can just work with:
> > NCalc -> Assembly not published to NuGet, (but if someone wants we can), with all shared business logic. NCalcSync -> Assembly with `Expression` and `EvaluationVisitor` NCalcAsync -> Assembly with `AsyncExpression` and `AsyncEvaluationVisitor`
> 
> As much as I like the approach of making things more clear, I don't like the usability aspect of it and feels like it leans towards the nodejs package hell. I'd personally prefer keeping things in the same package as much as possible.

I agree with you, also we would have dependency hell with DependencyInjection pointing to the two packages.

**Comment by gumbarros** [comment]
@ThomasHambach but question, today the name of the package is NCalcSync, should it have async support?

**Comment by ThomasHambach** [comment]
I dont see why not. We can add a (red?) banner on top of NcalcAsync to mention they need to switch the NcalcSync library. Especially if they are so similar anyways. Most packages have both sync and async in the same repo. The naming is unfortunate but not much we can do about that.

**Comment by gumbarros** [comment]
> I dont see why not. We can add a (red?) banner on top of NcalcAsync to mention they need to switch the NcalcSync library. Especially if they are so similar anyways. Most packages have both sync and async in the same repo. The naming is unfortunate but not much we can do about that.

Not a fan of NCalcSync doing both, but also not a fan of two packages for such a small things. The big villain I think is NuGet not allowing renaming lol.

**Comment by gumbarros** [comment]
Also should this be a v4.3 or a v5 milestone (v4.2 already too big I think)?

**Comment by Bykiev** [comment]
> Also should this be a v4.3 or a v5 milestone (v4.2 already too big I think)?

v4.2 is really big, vote for v4.3

**Comment by gumbarros** [comment]
The strategy of handling async changed. `VisitAsync` is required and there is no way to escape. In compensation, `Result` still can be an object.

I loved the result. Single assembly for NCalc, just `AsyncEvaluationVisitor` with `async` logic. But still don't like the NCalcSync name if the library also does async lol.
