### ISSUE TITLE
Re-add Antlr as a plugin

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#173]
**Is your feature request related to a problem? Please describe.**
No, but can help debug of future problems

**Describe the solution you'd like**
Implement `ILogicalExpressionFactory` with the old parser

**Describe alternatives you've considered**
None 

**Additional context**
Just for fun and a good example of how to implement another parser.

**Comment by ThomasHambach** [comment]
Hi @gumbarros , this looks like a cool feature. Do you have an example of the alternative implementation or did I just miss it?

**Comment by gumbarros** [comment]
Yes, you can check the docs at Plugins/Antlr
