### ISSUE TITLE
Use NCalc org at NuGet packages

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#180]
@yallie I invited you to the NCalc org. Can you add the unsigned version to the org?

![image](https://github.com/ncalc/ncalc/assets/52143624/034dd794-f9fa-4370-9b5c-ae78b758cb42)

Also, I will update the package descriptions and logo at the new packages in a PR this week.

**Comment by yallie** [comment]
>Can you add the unsigned version to the org?

Hi @gumbarros!
Added both NCalcSync and NCalcAsync.
Didn't know that nuget.org has organizations 😲

**Comment by gumbarros** [comment]
Thanks!
