### ISSUE TITLE
System.InvalidOperationException: 'Operator '*' not implemented for operands of types and '

### ISSUE THREAD

**Issue by Beckdotan** [ncalc/ncalc#194]
when calculating expression like "DP(5186)*if(DP(90)>0,CFP(90),0.49)/1000" Where DP and CFP are costum function I have, when I get to the level of * I get the error in the title. 

This might be due to the fact that I'm creating my own visitor and as suggested instead of ovveride I wrote new as suggested for v4? 

Here is a document with all the logic of my code and how it works including all the changes I have made for v4 as refrence. 

https://dotnetfiddle.net/9vWQ3T

**Comment by Bykiev** [comment]
It seems on of the value is null? It'll be supported in v4.2 https://github.com/ncalc/ncalc/pull/184

**Comment by Beckdotan** [comment]
@Bykiev I have implemented my own visitor to deal with null values.  (i'm dealing with them in some cases differently then you will). 

here is the code: 

/// <summary>
///  calculating expression recursively, according to the Operators logic below. 
/// </summary>
/// <param name="expression"></param>
public new void Visit(BinaryExpression expression)
{
  var myOperations = new[]
  {
    BinaryExpressionType.Plus,
    BinaryExpressionType.Minus,
    BinaryExpressionType.Times,
    BinaryExpressionType.Div,
    BinaryExpressionType.Modulo,
    BinaryExpressionType.And,
    BinaryExpressionType.Or,
    BinaryExpressionType.Equal,
    BinaryExpressionType.NotEqual,
    BinaryExpressionType.Greater,
    BinaryExpressionType.GreaterOrEqual,
    BinaryExpressionType.Lesser,
    BinaryExpressionType.LesserOrEqual

  };

  if (!myOperations.Contains(expression.Type))
  {
    base.Visit(expression);
    return;
  }

  expression.LeftExpression.Accept(this);
  var left = Result;

  expression.RightExpression.Accept(this);
  var right = Result;

  switch (expression.Type)
  {
    // if both right and left are null return null else null counts as 0
    case BinaryExpressionType.Plus:
      if (left == null && right == null)
      {
        Result = null;
      }
      else
      {
        Result = MathHelper.Add(left ?? 0d, right ?? 0d, CultureInfo);
      }
      break;

    //  if both right and left are null return null else null counts as 0
    case BinaryExpressionType.Minus:
      if (left == null && right == null)
      {
        Result = null;
      }
      else
      {
        Result = MathHelper.Subtract(left ?? 0d, right ?? 0d, CultureInfo);

      }
      break;

    // presence of null in each of the sides causes null return
    case BinaryExpressionType.Times:
      Result = (left == null || right == null) ? null :
        MathHelper.Multiply(left, right, CultureInfo);
      break;
      
      
      but in the version 4, it doesn't seem to enter there, (when i put a stopping point in the BinaryExpressionType.Times it doesn't stop there before the error happens. 
      maybe its due to the fact that I needed to change the visitor instead to be overried to be new?

**Comment by gumbarros** [comment]
Can you send the complete exception? Sounds like one at `MathHelper`, like you are trying to multiply 2 incompatible types.

**Comment by Beckdotan** [comment]
This is solved, I think it was due to the problem I needed to update my own evaluateVisitor to be with c# 8.0 syntax.
