### ISSUE TITLE
NuGet for ncalc/ncalc

### ISSUE THREAD

**Issue by MattPWills** [ncalc/ncalc#20]
Hi 
Appologies if this is a noob question, but I can't find a NuGet package for ncalc/ncalc 
I can only find the async one https://www.nuget.org/packages/NCalcAsync/
Am I missing something?

**Comment by yallie** [comment]
Hi Matt,

sorry for my late reply. Here is the Nuget package: https://www.nuget.org/packages/NCalcSync

Regards, Alex

**Comment by MattPWills** [comment]
Thanks @yallie in the meantime I got the async version working, so all good - great component. Starting some load testing today👍 Thanks for all your work on it.

**Comment by yallie** [comment]
Great! I believe async version covers more use cases and should be preferred for the new applications :)
