### ISSUE TITLE
Create a new icon for the project

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#205]
If the community agree and someone with arts knowledge wants to do the challenge :)

My suggestion would me something like the .NET logo vibes with math, not so different from the current.

Reason:
I have nothing against the current logo, but it's just a generic png from a reverse search:
![image](https://github.com/ncalc/ncalc/assets/52143624/99fb9813-af21-4dd6-83d8-e1d01f7b287b)

Would be nice to have something unique for the project and use it at README.md.

**Comment by Beckdotan** [comment]
@gumbarros  I'll do it next week!

**Comment by Beckdotan** [comment]
@gumbarros 

Please let me know if you like this direction, so I can continue to refine it. 


![openart-image_qk-TPnBX_1717920530765_raw](https://github.com/ncalc/ncalc/assets/78174171/72b22e67-3f63-4c04-ad39-1a631787eb7b)
![openart-image_z6ZfZjWd_1717920453154_raw](https://github.com/ncalc/ncalc/assets/78174171/244a445b-64d1-4fef-83af-2a3ad80b3709)
![openart-image_cQoE7T6L_1717920242117_raw](https://github.com/ncalc/ncalc/assets/78174171/c43e3ba5-5ec8-4586-8cb2-881c41c90266)

**Comment by gumbarros** [comment]
@Beckdotan Sorry, I don't like AI-generated images for jobs like this (I saw that you used openart.ai by the url). 

@Bykiev @yallie I made this on GIMP, was thinking in just an evolution of the current logo using the .NET color. Can we use it at 4.3 or want new suggestions?
![ncalc](https://github.com/ncalc/ncalc/assets/52143624/1efb2306-89e4-48e8-a11f-80ba0be36e74)

**Comment by Beckdotan** [comment]
@gumbarros  no problem! I wanted to use the AI for ideation and than create one properly in photoshop. 
I see that you wants something more similar to what you have already got! 
I'm on it. are there any specific colors you want me to use?

**Comment by Bykiev** [comment]
> @Beckdotan Sorry, I don't like AI-generated images for jobs like this (I saw that you used openart.ai by the url).
> 
> @Bykiev @yallie I made this on GIMP, was thinking in just an evolution of the current logo using the .NET color. Can we use it at 4.3 or want new suggestions? ![ncalc](https://private-user-images.githubusercontent.com/52143624/337978897-1efb2306-89e4-48e8-a11f-80ba0be36e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTU3MDMsIm5iZiI6MTcxNzk1NTQwMywicGF0aCI6Ii81MjE0MzYyNC8zMzc5Nzg4OTctMWVmYjIzMDYtODllNC00OGU4LWExMWYtODBiYTBiZTM2ZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE3NTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZWRkYzQ5NWE1NGQzNDAxNmUwZmRiODE0N2Y5OGViNDNjOTEwNmE4NjgwNmViNmQ2NjM1MjU1NTk1YTQ5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvaCXNM1vqmBIsYMJfdZGEFP8HTEJ3Sgy2nD7SREJg8)

Sorry, I don't like both of them... Maybe one more try?

**Comment by gumbarros** [comment]
> @gumbarros  no problem! I wanted to use the AI for ideation and than create one properly in photoshop. 
> I see that you wants something more similar to what you have already got! 
> I'm on it. are there any specific colors you want me to use? 

Probably something minimalist and related to math like the current logo, I like it

**Comment by yallie** [comment]
Hi guys!

First of all, thanks a lot for your amazing recent work on ncalc!
My original intent was just to keep the code up to date with .NET and fix bugs.
But you brought the new life to the nearly abandoned project — that's awesome 🔥

Now for the logo.

Codeplex version of ncalc didn't have any, so I just used a generic open-source icon.
Combining ncalc with .NET foundation image would be something like

<img src="https://github.com/ncalc/ncalc/assets/672878/5a3f7d74-b098-4b94-aa05-479c0765dc62" width="200" height="200"/>


But .NET logo has changed over the years:

----  

<img src="https://github.com/ncalc/ncalc/assets/672878/fed68ef3-6edc-4fbc-b887-ded5706ac736" width="100" />
<img src="https://github.com/ncalc/ncalc/assets/672878/ab4e56ca-2b84-4d3c-9e29-d0f1afc51c37" width="100" />
<img src="https://github.com/ncalc/ncalc/assets/672878/8d122a5e-5bc0-41b1-908f-a07897211989" width="100" />
<img src="https://github.com/ncalc/ncalc/assets/672878/70da0411-054c-4b52-aa93-e009930d8078" width="100" />

----

— and it's pretty likely that it will keep on changing.

Not sure if we should try to keep up with it every time they would do rebranding...

**Comment by gumbarros** [comment]
> Hi guys!
> 
> First of all, thanks a lot for your amazing recent work on ncalc! My original intent was just to keep the code up to date with .NET and fix bugs. But you brought the new life to the nearly abandoned project — that's awesome 🔥
> 
> Now for the logo.
> 
> Codeplex version of ncalc didn't have any, so I just used a generic open-source icon. Combining ncalc with .NET foundation image would be something like
> 
> <img alt="" width="200" height="200" src="https://private-user-images.githubusercontent.com/672878/338013762-5a3f7d74-b098-4b94-aa05-479c0765dc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzU2OTEsIm5iZiI6MTcxNzk3NTM5MSwicGF0aCI6Ii82NzI4NzgvMzM4MDEzNzYyLTVhM2Y3ZDc0LWIwOTgtNGI5NC1hYTA1LTQ3OWMwNzY1ZGM2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDgxYTdhOGQ1NTAxNzIzZmFmNGU3NmRiZDkyMzExZGVlMDJhMDNkYTUwNzQzOGJkNjY4ZDJlNzI5YzM2OTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9WkYCQTD_WRowtQkgpVfBwajBQIZhR39ty7_3VI8Hc4">
> But .NET logo has changed over the years:
> 
> <img alt="" width="100" src="https://private-user-images.githubusercontent.com/672878/338014052-fed68ef3-6edc-4fbc-b887-ded5706ac736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzU2OTEsIm5iZiI6MTcxNzk3NTM5MSwicGF0aCI6Ii82NzI4NzgvMzM4MDE0MDUyLWZlZDY4ZWYzLTZlZGMtNGZiYy1iODg3LWRlZDU3MDZhYzczNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2U4ZTU0NDdhZThkYjQ2ZTliOWViZDQ3MTA1OTQ3MzE4NmIwYWMxZDgzMWM0OWViNjkxMGQ3ZjE5ODYxM2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uaqGvtzxL3WHCuTlUzOF5UokiKGGshq1LWoStkdaH4o"> <img alt="" width="100" src="https://private-user-images.githubusercontent.com/672878/338014694-ab4e56ca-2b84-4d3c-9e29-d0f1afc51c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzU2OTEsIm5iZiI6MTcxNzk3NTM5MSwicGF0aCI6Ii82NzI4NzgvMzM4MDE0Njk0LWFiNGU1NmNhLTJiODQtNGQzYy05ZTI5LWQwZjFhZmM1MWMzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGY3MDU1OWY1ZmIxZDY4ZTg0ZjFkZWUyNjQ5NDU4YzMxZGVmYWZkN2QxYzkwZDYyZjczMzYzNmU3ZmY3YjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ml2iGJCFN_PdW-pdCeJaedJR27zUDXt-Xwa4xgSWqOM"> <img alt="" width="100" src="https://private-user-images.githubusercontent.com/672878/338014122-8d122a5e-5bc0-41b1-908f-a07897211989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzU2OTEsIm5iZiI6MTcxNzk3NTM5MSwicGF0aCI6Ii82NzI4NzgvMzM4MDE0MTIyLThkMTIyYTVlLTViYzAtNDFiMS05MDhmLWEwNzg5NzIxMTk4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWMxYzI1OTkyNmY4Y2Y1Njg5NGE3Yjg2YzQ2Yzg2N2Q3NTMwODY3ZDc2ZjFkYmE2YWFmMjA5YTViODY1YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lP5Vm5ucSkbMY1r2MWFWNMnqRG6Vfy3MZqybz91Mw4Q"> <img alt="" width="100" src="https://private-user-images.githubusercontent.com/672878/338014149-70da0411-054c-4b52-aa93-e009930d8078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzU2OTEsIm5iZiI6MTcxNzk3NTM5MSwicGF0aCI6Ii82NzI4NzgvMzM4MDE0MTQ5LTcwZGEwNDExLTA1NGMtNGI1Mi1hYTkzLWUwMDk5MzBkODA3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQyMzIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmJhOTliYmY3MmI2NmM1Nzc2NjEzYTdjM2I3NjM2MmNhZDRjYTk5YmMxYzc5MmE2NmNkZDdiMjRkMWMwOTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hz9URtELLUqaPDSPKBzr799QZC1u4wuhaNPUuSrTk7Q">
> — and it's pretty likely that it will keep on changing.
> 
> Not sure if we should try to keep up with it every time they would do rebranding...

I liked the idea and concept and we should keep exploring it, but idk if the color scheme is good with the original icon, but I want to explore more something related to .NET colors (because of the N) and math (Calc)
