### ISSUE TITLE
Checked Math

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#206]
Add CheckedMath from NCalc2, just this option is missing.

**Additional context**
Already implemented at `LambdaExpressionVisitor`, but `MathHelper` is not prepared. Not a priority for me, but if someone is interested, a PR is welcome :)

**Comment by Bykiev** [comment]
I've seen the `NCalc2` implementation and I don't like it as it's working only for integers and `checked` statement is not working with floating point types (they have infinity). We should handle FP overflow too
