### ISSUE TITLE
Breaking changes of the expression's evaluation 

### ISSUE THREAD

**Issue by laszlo-voros** [ncalc/ncalc#208]
Since version 4 and switching to Parlot evaluates an Expression as valid, even if it is not.
``` csharp
            Expression expression = new Expression("1.3,4.5");
            var result = expression.Evaluate(); // result is 1.3
```
This evaluates to 1.3. in the prior version with antlr it has thrown an exception.
Insted of lying and giving a apparently correct result, it would be correct to inform the user, that his input was not valid.

**Comment by gumbarros** [comment]
Hi @laszlo-voros, I tried to debug and find a solution but no success.

You can use [the ANTLR plugin](https://ncalc.github.io/ncalc/articles/plugins/antlr.html) while we track the issue.

**Comment by Bykiev** [comment]
@sebastienros, can you please help with handling such invalid expression?

**Comment by sebastienros** [comment]
My theory is that the parser expects an `expression` as its main element. In the case you share it will find `1.3` as this is the only `expression` (a `primary` actually) that works out. If the input was `1.3+1.2` then the result would be a `binaryexpression` with two `primary`.

To tell the parser that the whole thing should be an `expression`, you can just add an `.And(Eof())` such that if you read an `expression` and you are not at the end of the string then it must be a problem.

**Comment by sebastienros** [comment]
so `Parser = expression.And(Eof()).Compile()` or close to this.
