### ISSUE TITLE
(new Expression("0.05")).Evaluate() returns 0.5 and not 0.05?

### ISSUE THREAD

**Issue by iancoetzer** [ncalc/ncalc#214]
**Describe the bug**
When evaluation this expression the value returned missed the first 0 after the decimal point?

**Example Expression**
(new Expression("0.05")).Evaluate()
= 0.5

And another example
(new Expression("5000 * 0.05")).Evaluate()
returns 2500 instead of 250?

![image](https://github.com/ncalc/ncalc/assets/7976311/d58eb738-af41-43c2-b930-a3db532823d5)

**Comment by Bykiev** [comment]
Nice catch, any zeros after floating point are removed when parsed as integer (to handle the cases like this: `.4 (treats as 0.4)` we parsing the fp numbers as `integer dot integer`. I'll look what can I do...

**Comment by iancoetzer** [comment]
excellent thank you!
