### ISSUE TITLE
My Own MyCalcVisitor : EvaluationVisitor Is not being Called

### ISSUE THREAD

**Issue by Beckdotan** [ncalc/ncalc#219]
Hi, Since the 4.0 changes I have hard times to migrate. 
After doing everything you suggested here: https://github.com/ncalc/ncalc/issues/148

and than the problems with the stackoverflow (that wasn't solved yet as well), I was finally able to see more of what is going on, and I found out that MyCalcVisitor that implements EvaluationVisitor , isn't called although this is the visitor that I pass to the  
    static object[] EvaluateArray(string expression,  MyCalcVisitor visitor)
    {
      var expr = LogicalExpressionFactory.Create(expression);
        expr.Accept(visitor);
}

But the default public class EvaluationVisitor : IEvaluationVisitor of NCalc is being called. 

now the IEvaluationVisitor implements ILogicalExpressionVisitor which implements ILogicalExpressionVisitor

but my main problem with implementing the IEvaluationVisitor  with MyCalcVisitor is that in the ILogicalExpressionVisitor  there is syntax that is allowed only from c# 8.0 and I have 7.3 and cannot migrate yet. 

I assume that since my MyCalcVisitor is currently implementing EvaluationVisitor  and not IEvaluationVisitor  it will not run? any suggestions?

**Comment by gumbarros** [comment]
> But the default public class EvaluationVisitor : IEvaluationVisitor of NCalc is being called.

If you want to call your own visitor, read the docs, this is supported via DI.
https://ncalc.github.io/ncalc/articles/dependency_injection.html#withevaluationvisitor

There is an example of this concept working at the unit tests
https://github.com/ncalc/ncalc/blob/c1a20826046905237dca4ff9a9b975aa68243f3d/test/NCalc.Tests/ServiceCollectionExtensionsTests.cs#L74

> but my main problem with implementing the IEvaluationVisitor with MyCalcVisitor is that in the ILogicalExpressionVisitor there is syntax that is allowed only from c# 8.0 and I have 7.3 and cannot migrate yet.

Just add <LangVersion>12</LangVersion> at your .csproj and install [Polysharp](https://github.com/Sergio0694/PolySharp). The C# version does not affect the .NET runtime version.

**Comment by Beckdotan** [comment]
@gumbarros  Thanks, Ill work on out tomorrow and will let you know.

**Comment by Beckdotan** [comment]
@gumbarros  working as you said. thanks.
