### ISSUE TITLE
Breaking change in v4.2.1: Expressions ending with space(s) throw

### ISSUE THREAD

**Issue by axunonb** [ncalc/ncalc#222]
This is a breaking change from v4.2.0 to v4.2.1:
If the expression ends with space(s) an `NCalcParserException` throws
```
"11+33" => success (no spaces)
" 11+33" => success (starts with space)
" 11+33 " => throws NCalc.Exceptions.NCalcParserException : Invalid token in expression at position (1:9) (starts/ends with space)
"11+33 " => throws (ends with space)
```
This is true for all cases in our unit tests, no matter what's inside the expression string.

Expected: Keep behavior of v4.2.0 - appended spaces should be ignored

**Comment by Bykiev** [comment]
Thanks, this was a not an intended change, will be fixed in the next update.
