### ISSUE TITLE
Breaking Change in 4.2.1 - not<nospace>(true) throws UnknownFunction

### ISSUE THREAD

**Issue by gajanak** [ncalc/ncalc#226]
**Describe the bug**

The behavior has changed - expression with no space between not and a brace () throws a unknown function not.
Previos behavior was  'not ( true )' return false.
 

**Example Expression**
 'not( true )'  throws
 'not ( true )'  return false
 
 Should be added to Breaking Changes, or could not be handled as Operator instead function ?

**Comment by Bykiev** [comment]
Thank you, this is not an intended change, going to fix in the next update

**Comment by gumbarros** [comment]
> @gumbarros, I can't modify parser to fix this case, but we can add a function `Not()`, but it makes `not` operator case-sensitive when used with parenthesis. What do you think?

Feels hacky, but I don't see other way, I will try to fix the parser
