### ISSUE TITLE
Refactor expression arguments

### ISSUE THREAD

**Issue by sebastienros** [ncalc/ncalc#229]
The functions are passed as delegates on every expression instantiation. This is sub-optimal, instead a user should be able to register the methods once and then reuse this registration.

The way I do it in [Fluid](https://github.com/sebastienros/fluid) is by defining a global object `FluidOptions` that can be shared across expression instances. You could then create other specific option instances by copy like `new FluidOptions(baseOptions)` if you want to inherit from common options but change a single thing. This could then be used for all the options of an expression, including culture, arguments, ...

The instance should be thread-safe for read operations so it can be made static an shared.

**Comment by gumbarros** [comment]
@sebastienros I think we can re-use this class right?

https://ncalc.github.io/ncalc/api/NCalc.ExpressionContext.html

For the functions I was thinking in something like this:
```
public interface IFunction
{
    public string Name { get; }

    public object Evaluate(object[] arguments, ExpressionContext context);
}
```

**Comment by sebastienros** [comment]
Not sure I would introduce a new interface. Instead I would go for simplicity with a `Dictionary<string, Func<IReadOnlyList<Expression>, object>>`. This way you can just assign named Funcs, and also alter them.

In Fluid the CultureInfo is part of the options class. A class named `...Options` would be the best IMO as it conveys its intent (by convention in .NET too)

**Comment by gumbarros** [comment]
I was thinking more and stumbled at how to to dynamic parameters, and then I concluded, dynamic parameters does not make sense. 

What is the benefit of doing this:

```
expression.EvaluateParameter += delegate(string name, ParameterArgs args)
  {
    if (name == "Pi")
        args.Result = 3.14;
  };
```

When you can just:
`expression.Parameters["Pi"] = 3.14`

The first option is just more verbose and create performance overhead using event handling. If someone really wants to execute C# code to a parameter, it would be possible using a `Dictionary<string, Func<object>>`, but IDK if it's worth.

**Comment by sebastienros** [comment]
That's what I had in mind too. You may want to provide the Options object itself as an argument, such that functions and arguments could provide different values based on other options.

**Comment by yallie** [comment]
> What is the benefit of doing this:
> 
> ```csharp
> expression.EvaluateParameter += delegate(string name, ParameterArgs args)
>   {
>     if (name == "Pi")
>         args.Result = 3.14;
>   };
> ```
> 
> When you can just: `expression.Parameters["Pi"] = 3.14`

I thought it's for non-deterministic parameters like "now" or "random".

**Comment by gumbarros** [comment]
> > What is the benefit of doing this:
> > ```cs
> > expression.EvaluateParameter += delegate(string name, ParameterArgs args)
> >   {
> >     if (name == "Pi")
> >         args.Result = 3.14;
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When you can just: `expression.Parameters["Pi"] = 3.14`
> 
> I thought it's for non-deterministic parameters like "now" or "random".

Hmmm, good point, but a counterpoint, I also use `now` at my systems, but I use as a function (`now()`), random also makes more sense as a function (in C# it's a function). In my humble opinion, I think parameters should be stateless.

**Comment by sebastienros** [comment]
You never know, someone might use the fact it's a Func to initialize the value lazily, or to do some tracing about when properties are used.

**Comment by sebastienros** [comment]
Another option would be to expose methods to add parameters instead of the raw Dictionary, like 

```c#
AddParameter(object value);
AddParameter(Func<object> factory);
AddParameter(Func<NCalcOptions, object> factory);
```

And internally store a dictionary or `Func<NCalcOptions, object>` for every cases.

**Comment by gumbarros** [comment]
An impediment. We have NCalcSync and NCalcAsync, where each assembly has only the [Expression](https://ncalc.github.io/ncalc/api/NCalc.Expression.html) and [AsyncExpression](https://ncalc.github.io/ncalc/api/NCalc.AsyncExpression.html) classes respectivaly.

Can be this solved this way?

At NCalc.Core (shared assembly):
```cs
public abstract class ExpressionContextBase
{
    public ExpressionOptions Options { get; set; } = ExpressionOptions.None;
    public CultureInfo CultureInfo { get; set; } = CultureInfo.CurrentCulture;

    protected ExpressionContextBase()
    {
        
    }
}
```

At NCalc.Sync:
```cs
public class ExpressionContext : ExpressionContextBase
{
    public static readonly ExpressionContext Default = new();
    
    public Dictionary<string, object?> StaticParameters { get; } = new();
    public Dictionary<string, Func<object?>> DynamicParameters { get; } = new();
    
    public Dictionary<string, Func<Expression[],object?>> Functions { get; } = new();

    //We can also make the properties private and add the helper methods like the example below...
    
    public void AddParameter(string name, object value)
    {
        StaticParameters[name] = value;
    }
}
```

At NCalc.Async:
```cs
public class AsyncExpressionContext : ExpressionContextBase
{
    public static readonly AsyncExpressionContext Default = new();
    
    public Dictionary<string, Task<object?>> StaticParameters { get; } = new();
    public Dictionary<string, Func<Task<object?>>> DynamicParameters { get; } = new();
    
    public Dictionary<string, Func<AsyncExpression[],Task<object>>> Functions { get; } = new();
}
```

Btw, I also like the name `ExpressionOptions` more, but it's already taken by [this enum](https://ncalc.github.io/ncalc/api/NCalc.ExpressionOptions.html) (previously know as `EvaluateOptions`, but it was renamed because it's also used at caching and parsing)
