### ISSUE TITLE
Managing Numeric Input Separators in a Multilingual Environment

### ISSUE THREAD

**Issue by attiqeurrehman** [ncalc/ncalc#231]
Hi, 

In our application, we've encountered a challenge related to supporting multiple languages. Users often input numbers with commas, leading to complications. To streamline our processes, we've adopted a workaround of treating semicolons as parameter separators instead of commas and then performing a replacement before evaluation.

I'm curious about whether it's feasible to implement this behavior directly within the library itself. Are there any recommended approaches or best practices for achieving this more seamlessly? Any insights or guidance would be greatly appreciated.

**Comment by gumbarros** [comment]
Duplicated of #119

**Comment by attiqerehman** [comment]
@gumbarros any plans for it? 

-A
