### ISSUE TITLE
Undesired behavior when using with Blazor Webassembly 

### ISSUE THREAD

**Issue by vgarant** [ncalc/ncalc#232]
Hi!

Context: In Blazor Web Webassembly when doing a **Console.Error.WriteLine()**, It writes the output to the browser console as expected, but because it's an error message (Console.Error), it also displays another message at the bottom of the web page: 
> "An unhandled error has occurred. Reload".

I believe this is the expected behaviour of Blazor.

The problem is that ncalc-async is using **Console.Error** to display errors.

This can be seen in the constructor of the class **NCalcParser**:

`public NCalcParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }`

This causes that, when there is an error in the **ncalc parser** , it shows the message in **Console.Error** causing an error message in the Blazor page.

Is there any way to tell **ncalc-async** not to display errors with Console.Error?

or directly not to show anything by console, removing the default listeners of the **antlr4** library, for example:
```
var errorListenerParser = new ErrorListenerParser();
parser.RemoveErrorListeners();
```

**Comment by gumbarros** [comment]
@vgarant can you check if it happens at v5?

**Comment by gumbarros** [comment]
"An unhandled error has occurred. Reload" is a generic Blazor message. The user is also not using the latest version of NCalc. Closing due inactivity.
