### ISSUE TITLE
Incorrect evaluation of double type values

### ISSUE THREAD

**Issue by mechanicCatman** [ncalc/ncalc#235]
**Describe the bug**
Hi! I have an expression("1.0001334543"). When I try to evaluate this expression, I get "1.1334543" instead of "1.0001334543". This also happens with any other expressions that have zeros after the decimal point. Significant digit are always removed. It happens after updating to version 4.0.0 and higher.

**Comment by Bykiev** [comment]
Hi, this was already fixed in v4.2.1. Can you please update and confirm no issues?

**Comment by mechanicCatman** [comment]
> Hi, this was already fixed in v4.2.1. Can you please update and confirm no issues?

Yes, confirm no issues. Sorry, I didn't see the new version.
