### ISSUE TITLE
`AsyncExpression` is missing `HasErrors`

### ISSUE THREAD

**Issue by gmcchessney** [ncalc/ncalc#239]
`AsyncExpression` is missing the `HasErrors` method. This method was available in the NCalcAsync repo. I don't see any documentation or discussion about why this was removed, so I assume it wasn't intentional.

**Comment by gumbarros** [comment]
@gmcchessney Not intentional, `AsyncExpression` was re-written from zero and I forgotten. I will add again tonight and release 4.3.1
