### ISSUE TITLE
Whitespace causes parser to ignore invalid syntax

### ISSUE THREAD

**Issue by gmcchessney** [ncalc/ncalc#240]
Add these three expressions to `ExceptionTests.Should_Throw_Parse_Exception()`:
```cs
[InlineData("42 a")]
[InlineData("42 '")]
[InlineData("Abs(-1) ]")]
```

The test will fail because the parser thinks these are valid expressions.

Interestingly, if you remove the spaces from the expressions the test will pass.

**Comment by Bykiev** [comment]
Hi, thank you, will try to fix it asap
