### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by viceice** [ncalc/ncalc#25]
I can't update to this new version, because i need signed assemblies (using net472). 

I need to copy that assembly to the GAC, because i use it in a SharePoint on-premise project.

**Comment by drcolombo** [comment]
Hello,

Guys, could you please sign the assemblies provided within NuGet package? As @viceice already said - it's impossible to reference them in a project that is signed - you will get a run-time error saying `"Could not load file or assembly 'NCalc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required"`.

**Comment by yallie** [comment]
Hello, sorry for my late reply!

I'd like to avoid adding a strong name to the published package.
Isn't it an option to use the strong-name signer nuget package [such as this one](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/) in your projects?

**Comment by axunonb** [comment]
@yallie First of all thanks for keeping up this wonderful project!

We'd like to reference NCalc in an OSS project, where we deploy signed assemblies of the library. As far as we understand, the signer packages mentioned above would have to be referenced in the **target** project. At least, this is what we see with our unit tests.

Other OSS projects sometimes deploy signed **and** unsigned packages on NuGet. Wouldn't that be feasible option?
We'd really prefer a signed package over forking the NCalc source into our project. Any chance?
