### ISSUE TITLE
Use GitHub actions

### ISSUE THREAD

**Issue by sebastienros** [ncalc/ncalc#258]
This will provide much faster builds than appveyor. Here is how I added it to Irony to replace appveyor: https://github.com/IronyProject/Irony/pull/60/files

Another example for Parlot: https://github.com/sebastienros/parlot/blob/main/.github/workflows/build.yml
And how Parlot is deployed on NuGet by just creating a new tagged release in GH: https://github.com/sebastienros/parlot/blob/main/.github/workflows/publish.yml

**Comment by gumbarros** [comment]
We already use GH for build and tests. NuGet is also deployed from a new tagged release.

So this is a duplicated of #247?

**Comment by sebastienros** [comment]
I see, so we just need to remove the appveyor tasks?

**Comment by gumbarros** [comment]
> I see, so we just need to remove the appveyor tasks?

Yes, I didn't remove it because I didn't understand why the project have both GH and appveyor, so I assumed it was for codecov.

But as I said in the edit, I didn't find any useful data on appveyor.
