### ISSUE TITLE
A mention for PanoramicData.NCalcExtensions?

### ISSUE THREAD

**Issue by davidnmbond** [ncalc/ncalc#26]
Hi there,

We love NCalc and have been extending it to handle many general functions, including string functions, switch, if, in, typeOf, cast etc.

Perhaps you could give our project a mention in your readme?

The Github repo and documentation can be found here: https://github.com/panoramicdata/PanoramicData.NCalcExtensions
The Nuget package is PanoramicData.NCalcExtensions and can be found here: https://github.com/panoramicdata/PanoramicData.NCalcExtensions

Keep up the great work!

David, Dan and all at Panoramic Data

**Comment by yallie** [comment]
Sure, thanks!
The library looks great! 👍 

Added the Related projects section to the README.
Feel free to change the description as needed and send a PR.
