### ISSUE TITLE
Pow should return decimal

### ISSUE THREAD

**Issue by xcaptain** [ncalc/ncalc#265]
https://github.com/ncalc/ncalc/blob/0abc655714a46b443328ec6bc387a4f1dd56155d/src/NCalc.Core/Helpers/MathHelper.cs#L414-L419

my test code:
```C#
using NCalc;

string input = "3.1 ** 2";
Expression e = new (input, ExpressionOptions.DecimalAsDefault);
var obj = e.Evaluate();
Console.WriteLine(obj.ToString());
```

Expected result should be: 9.61, but I got: `9.610000000000001`

I think when doing pow, if `DecimalAsDefault` is set, and b is integer, the result should be decimal rather than double

**Comment by gumbarros** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.math.pow?view=net-8.0

Math.Pow returns a double by default. There is another issue regarding this, the workaround is creating a custom Pow function and use a third party lib to do decimal math.

**Comment by Bykiev** [comment]
I believe we can implement it with BigDecimal as it's already used in the project
