### ISSUE TITLE
Performance issue resurfaced

### ISSUE THREAD

**Issue by eero-dev** [ncalc/ncalc#267]
**Describe the bug**
Exactly same issue as described here: https://github.com/ncalc/ncalc/issues/51
The previous fix seems to be missing from the Core and Async variant libraries resulting in the same bug as described in the previous issue.
Resurfaced because of this change: https://github.com/ncalc/ncalc/pull/207

- Affects NCalc version 4.3.0 to 4.3.3
The bug is not present in version 4.2.1

Running my application is miserable now

I shouldn't have to see NCalc Trace output when debugging my application or in production
![image](https://github.com/ncalc/ncalc/assets/49983218/0e1f41a1-604c-4d46-93a3-647ce5b36cd3)

The fix is probably just adding `<DefineConstants>$(DefineConstants.Replace("TRACE", "NOTRACE"))</DefineConstants>` to the .csproj files

**Comment by gumbarros** [comment]
The problem is because the `<DefineConstants>$(DefineConstants.Replace("TRACE", "NOTRACE"))</DefineConstants>` is not defined at `NCalc.Core`, where the cache resides. A workaround is installing `NCalc.MemoryCache`, because it don't have `Trace`. I will create a PR to solve the problem.

**Comment by eero-dev** [comment]
This is back again

**Comment by gumbarros** [comment]
> This is back again

@eero-dev do you know which version this appeared again?


@Bykiev I vote to simply remove the Trace and use [`Microsoft.Extensions.Logging`](https://www.nuget.org/packages/Microsoft.Extensions.Logging/) and consumers decide how to enable or disable logging.
