### ISSUE TITLE
Slow execution on first call with Parlot

### ISSUE THREAD

**Issue by Bykiev** [ncalc/ncalc#282]
@gumbarros, right now the first call is too slow (on .NET Framework it takes more than 10 seconds on the first call). Can we make the expression compilation optional or maybe we can compile the expression on the app init?

**Comment by gumbarros** [comment]
> @gumbarros, right now the first call is too slow (on .NET Framework it takes more than 10 seconds on the first call). Can we make the expression compilation optional or maybe we can compile the expression on the app init?

What about just disabling compilation for .NET Framework? I think it's not possible to pass a parameter to the static ctor.

**Comment by Bykiev** [comment]
Sure, but what about static `Initialize` method?

**Comment by gumbarros** [comment]
> Sure, but what about static `Initialize` method or maybe a regular constructor?

A singleton with a private ctor and a `GetInstance` method would solve.

**Comment by Bykiev** [comment]
> A singleton with a private ctor and a `GetInstance` method would solve.

Sounds good, but what about `ILogicalExpressionFactory` interface? We can add a new `ExpressionOptions`, but as ANTLR is not supporting compilation, this option is not looking good. I'd like to avoid a new breaking changes. What do you think?

**Comment by gumbarros** [comment]
> > A singleton with a private ctor and a `GetInstance` method would solve.
> 
> Sounds good, but what about `ILogicalExpressionFactory` interface? We can add a new `ExpressionOptions`, but as ANTLR is not supporting compilation, this option is not looking good. I'd like to avoid a new breaking changes. What do you think?

This option would need somehow applied only for Parlot because would also not make sense for custom `ILogicalExpressionFactory` implementations. Something at the Parlot constructor like `IOptions` would work.

**Comment by Bykiev** [comment]
Would you like to contribute on this feature?

**Comment by gumbarros** [comment]
> Would you like to contribute on this feature?

I will take a time to think on this, you can give a try if you want.

**Comment by Bykiev** [comment]
Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)

**Comment by gumbarros** [comment]
> Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)

There is no warmup, because the static constructor is not called at `[GlobalSetup]`. I agree there should be a way to disable compilation. I thinking in some idea to enable or disable parser parts so performance can also improve.

**Comment by Bykiev** [comment]
> > Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)
> 
> There is no warmup, because the static constructor is not called at `[GlobalSetup]`. I agree there should be a way to disable compilation. I thinking in some idea to enable or disable parser parts so performance can also improve.

Well, then the first call should be excluded as outlier... 
Before your test you've just removed `Compile()` call from `LogicalExpressionParser`? I've tried it and it seems Parlot is faster without compilation or maybe I don't understand anything in coding (lol)?

**Comment by gumbarros** [comment]
> > > Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)
> > 
> > 
> > There is no warmup, because the static constructor is not called at `[GlobalSetup]`. I agree there should be a way to disable compilation. I thinking in some idea to enable or disable parser parts so performance can also improve.
> 
> Well, then the first call should be excluded as outlier... Before your test you've just removed `Compile()` call from `LogicalExpressionParser`? I've tried it and it seems Parlot is faster without compilation or maybe I don't understand anything in coding (lol)?

It's because the benchmark is considering the time for compiling the parser when it should be calculating the time for parsing a expression.

**Comment by Bykiev** [comment]
> > > > Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)
> > > 
> > > 
> > > There is no warmup, because the static constructor is not called at `[GlobalSetup]`. I agree there should be a way to disable compilation. I thinking in some idea to enable or disable parser parts so performance can also improve.
> > 
> > 
> > Well, then the first call should be excluded as outlier... Before your test you've just removed `Compile()` call from `LogicalExpressionParser`? I've tried it and it seems Parlot is faster without compilation or maybe I don't understand anything in coding (lol)?
> 
> It's because the benchmark is considering the time for compiling the parser when it should be calculating the time for parsing a expression.

Sorry, still don't understand. Static constructor is called only once and there is a Median column, so, it's shouldn't be a problem?

**Comment by gumbarros** [comment]
> > > > > Strange enough as it makes warm up before the benchmark execution or maybe I don't understand something? But anyway, there should be a way to disable compilation if not needed (or there are some issues with it)
> > > > 
> > > > 
> > > > There is no warmup, because the static constructor is not called at `[GlobalSetup]`. I agree there should be a way to disable compilation. I thinking in some idea to enable or disable parser parts so performance can also improve.
> > > 
> > > 
> > > Well, then the first call should be excluded as outlier... Before your test you've just removed `Compile()` call from `LogicalExpressionParser`? I've tried it and it seems Parlot is faster without compilation or maybe I don't understand anything in coding (lol)?
> > 
> > 
> > It's because the benchmark is considering the time for compiling the parser when it should be calculating the time for parsing a expression.
> 
> Sorry, still don't understand. Static constructor is called only once and there is a Median column, so, it's shouldn't be a problem?

It's because the static constructor is called at the benchmark, and it should not.

**Comment by gumbarros** [comment]
https://github.com/sebastienros/parlot/blob/main/test/Parlot.Benchmarks/JsonBench.cs

At this benchmark for example, the parser is compiled at `[GlobalSetup]` to prevent this issue.

**Comment by Bykiev** [comment]
We can call it in `[GlobalSetup]` too. I've tried, but results are the same

**Comment by Bykiev** [comment]
Based on Parlot's benchmarks [here](https://github.com/sebastienros/parlot#expression-benchmarks) the raw result for expressions is always better without compilation (almost 2x). So, I think, it should be disabled by default in NCalc.

**Comment by gumbarros** [comment]
> Based on Parlot's benchmarks [here](https://github.com/sebastienros/parlot#expression-benchmarks) the raw result for expressions is always better without compilation (almost 2x). So, I think, it should be disabled by default in NCalc.

No problem for me, for now we can disable compilation everytime and if someone really wants, just copy and paste the modified parser and inject it via DI.

**Comment by Bykiev** [comment]
Agreed. The new Parlot version released, there a lot of work here

**Comment by Bykiev** [comment]
I did some research and I think we can allow compilation via [AppContext.SetSwitch](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch?view=net-8.0). What do you think?

**Comment by gumbarros** [comment]
> I did some research and I think we can allow compilation via [AppContext.SetSwitch](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch?view=net-8.0). What do you think?

Nice idea, never heard about it, will do some re-search later. If you want to create a PR feel free too.

**Comment by Bykiev** [comment]
> > I did some research and I think we can allow compilation via [AppContext.SetSwitch](https://learn.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch?view=net-8.0). What do you think?
> 
> Nice idea, never heard about it, will do some re-search later. If you want to create a PR feel free too.

I'll make a PR. I've seen such feature in many projects, like efcore.pg
