### ISSUE TITLE
Construct expression with multiple EvaluationOptions

### ISSUE THREAD

**Issue by Bykiev** [ncalc/ncalc#30]
@yallie, first of all, thank you for this awesome library!

We need to use multiple `EvaluationOptions` to disable caching and enable IgnoreCase. It seems when `EvaluateOptions.NoCache | EvaluateOptions.IgnoreCase` is used the first one is ignored and only IgnoreCase is applied. How to apply both of them?

**Comment by yallie** [comment]
@Bykiev Hello, I'm not the author, all credits to Sébastien Ros :)
I just picked up the abandoned library and hosted it here because I use it in my projects.

>It seems when EvaluateOptions.NoCache | EvaluateOptions.IgnoreCase is used the first one is ignored and only IgnoreCase is applied. 

Looks like a bug.
Would you mind creating a unit test demonstrating the issue?
Thanks!

**Comment by Bykiev** [comment]
Thank you, I did some research and tests, but enums parsed correctly. For some reason, when the caching is enabled, it calcs incorrectly, but if `NoCache` option specified, all is working. When cache is disabled via `Expression` and EvaluateOptions.IgnoreCase specified it calcs incorrectly. Still investigating the issue...

**Comment by gumbarros** [comment]
@Bykiev can this be closed?

**Comment by Bykiev** [comment]
Yes, I don't remember, but it was solved in some version of NCalc
