### ISSUE TITLE
"ifs" Function throws FormatException

### ISSUE THREAD

**Issue by JEVietti** [ncalc/ncalc#304]
**Describe the bug**
See the Documentation for ifs [here](https://ncalc.github.io/ncalc/articles/functions.html)
NCalcSync Version="5.1.0"

I get a Format Exception using ifs as described in the documentation to supply a default value of string with ifs, however the string value works if it is not the default/last part of the statement. 

Also the example usage in the above documentation has an issue where if the value is 76 it is bar since the first expression is reached and resolved as true and returns, at least based on my testing with NCalcSync.

System.FormatException: String 'Ok' was not recognized as a valid Boolean.
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at NCalc.Helpers.BuiltInFunctionHelper.Evaluate(String functionName, Expression[] arguments, ExpressionContext context)
   at NCalc.Visitors.EvaluationVisitor.Visit(Function function)
   at NCalc.Domain.Function.Accept[T](ILogicalExpressionVisitor`1 visitor)
   at NCalc.Services.EvaluationService.Evaluate(LogicalExpression expression, ExpressionContext context)
   at NCalc.Expression.Evaluate()
   
**Example Expression**
Add the expression with your problem if applicable
My expression where I found this issue
`ifs([PToZnRatio] == null, null, [PToZnRatio] > 16, 'Limit', 'Ok')`	

This expression on the other hand works:
`if([PToZnRatio] == null, null, if([PToZnRatio] > 16, 'Limit', 'Ok'))	`

**Expression from documentation** also fails from my testing
`ifs(foo > 50, "bar", foo > 75, "baz", "quux")`
Exception:
System.FormatException: String 'quux' was not recognized as a valid Boolean.
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at NCalc.Helpers.BuiltInFunctionHelper.Evaluate(String functionName, Expression[] arguments, ExpressionContext context)
   at NCalc.Visitors.EvaluationVisitor.Visit(Function function)

**Comment by gumbarros** [comment]
Can you update to 5.2.0?

Everything working fine here:

```cs
    [Fact]
    public void Issue122()
    {
        var context = new ExpressionContext()
        {
            StaticParameters =
            {
                { "foo", 60 }
            }
        };
        Assert.Equal("bar", new Expression("ifs(foo > 50, \"bar\", foo > 75, \"baz\", \"quux\")", context).Evaluate());
    }
```

**Comment by JEVietti** [comment]
@gumbarros I'd like to and was attempting to but ran into another issue in #305. Also the test you wrote probably works either way but my expression did have AllowNullParameters as a part of the Context.

On a less important note the test doesn't prove that a foo value of 80 returns "baz" instead of bar, but again I think that's a documentation issue not a bug.

**Comment by gumbarros** [comment]
This is also working at v5.1

```cs
    [Fact]
    public void Issue304()
    {
        var context = new ExpressionContext
        {
            Options = ExpressionOptions.AllowNullParameter,
            StaticParameters =
            {
                { "PToZnRatio", 17 }
            }
        };
        Assert.Equal("Limit", new Expression(" if([PToZnRatio] == null, null, if([PToZnRatio] > 16, 'Limit', 'Ok'))\t", context).Evaluate());
    }
    ```

**Comment by JEVietti** [comment]
@gumbarros  Thanks for your effort on this, note I know that expression is working, that was the expression I said was working in my original report, I said the ifs expression was not working.

**Comment by Bykiev** [comment]
> @gumbarros Thanks for your effort on this, I know that expression is working, that was the expression I said was working in my original report, I said the ifs expression was not working.
> 
> This was the problem expression in 5.1 for me: ifs([PToZnRatio] == null, null, [PToZnRatio] > 16, 'Limit', 'Ok')

I've tried your expression with v5.1 and everything seems to be working.

```
string str = "ifs([PToZnRatio] == null, null, [PToZnRatio] > 16, 'Limit', 'Ok')";
var expr = new Expression(str, ExpressionOptions.AllowNullParameter, CultureInfo.InvariantCulture);
expr.Parameters["PToZnRatio"] = null;
var res = expr.Evaluate();
```

**Comment by Bykiev** [comment]
I've reproduced the issue with this expression:

`ifs(foo > 50, "bar", foo > 75, "baz", "quux")`

Seems it was not working in old versions too...

**Comment by Bykiev** [comment]
I've checked with 5.2.0 and can't reproduce the issue. Will release 5.2.1 soon
