### ISSUE TITLE
Evaluate() fails for 0.0 decimals in expression - Example "204.97-0.0000-0.00"

### ISSUE THREAD

**Issue by DavidRooney** [ncalc/ncalc#315]
**Describe the bug**
Updated the NCalcSync package from v3.12.0 to v5.2.1 and the following example now fails to evaluate when it worked in the previous version.
We have tried formatted the decimals to 2 and 1 decimal points with no success but we may have usecases that require better precision.

Any help would be greatly appreciated.

**Example Expression**
var formulaExpression = new Expression("204.97-0.0000-0.00");
var result = Convert.ToDecimal(formulaExpression.Evaluate());

**Exception:**
NCalc.Exceptions.NCalcParserException : Error parsing the expression.
  ----> NCalc.Exceptions.NCalcParserException : Invalid token in expression at position (1:16)

**Comment by DavidRooney** [comment]
Some investigation o pinpoint the version causing the error:
4.0.0 - Expressions still successfully evaluates
5.2.0 - Expressions still successfully evaluates
5.2.1 - Exception occurs

**Comment by Bykiev** [comment]
Hi, I was able to reproduce the issue since v.5.2.0. I'll check what is wrong, this seems to be a parser issue, because such expression is evaluates correctly: `204.97 - 0.0000 - 0.00`

**Comment by DavidRooney** [comment]
It didn't occur to me to test out putting spaces in. This is enough for us to move on so appreciate the testing of that

**Comment by Bykiev** [comment]
@DavidRooney, I've released v5.2.2 with a fix, it'll be available on NuGet in a minutes. Can you please confirm the issue is resolved?

**Comment by DavidRooney** [comment]
I can confirm this has resolved all of our issues. All tests green! thanks for fixing this so quickly
