### ISSUE TITLE
Comparing double and string fails

### ISSUE THREAD

**Issue by murksa** [ncalc/ncalc#32]
Evaluating e.g. the expression `1.0 == 'a'` fails with a "System.FormatException: Input string was not in a correct format."

**Comment by murksa** [comment]
Working on a fix for this I noticed that there are more issues in comparing types. For example, `4294967296.1 == 4294967296` evaluates to `true`. I will fix this and try to write an exhaustive set of tests comparing combinations of different types.

**Comment by yallie** [comment]
Hi @murksa,

>Evaluating e.g. the expression 1.0 == 'a' fails with a "System.FormatException: Input string was not in a correct format."

What do you think is the expected behavior?

>For example, 4294967296.1 == 4294967296 evaluates to true.

I agree that it looks weird, but that's a known problem of binary floating point types.
For example, plain C# program gives the same result, it prints `True`:

```csharp
class Program
{
	static void Main()
	{
		Console.WriteLine(4294967296.1f == 4294967296);
	}
}
```

**Comment by murksa** [comment]
> What do you think is the expected behavior?

I would expect `1.0 == 'a'` to be false and not to fail. (At least this is what the original NCalc evaluated to.)

**Comment by murksa** [comment]
Concerning the second problem, the following test succeeds:
```c#
Assert.IsTrue(4294967296.1f == 4294967296); // I didn't know about this!
Assert.IsFalse(4294967296.1d == 4294967296);
```

So, maybe my example was a bad one (altough I think NCalc uses doubles instead of floats if not told otherwise). What I actually wanted to demonstrate is that the following test fails:
```c#
var e = new Expression("x == y");
e.Parameters["x"] = 1.1d;
e.Parameters["y"] = 1L;

Assert.IsFalse((bool)e.Evaluate());
```

**Comment by gumbarros** [comment]
Working at latest version (v3.12) :)

![image](https://github.com/ncalc/ncalc/assets/52143624/d758d823-befc-46d5-bc98-50a95326e99d)
