### ISSUE TITLE
Abs dividing by decimal number throws execption

### ISSUE THREAD

**Issue by marcx28** [ncalc/ncalc#33]
If I try to calculate the absolute value of a number and then divide it by a decimal number, the program throws an `System.InvalidCastException`. This only happens using the abs function.

Code Example:
```
class Program {
    static void Main() {
        Expression e = new Expression("Abs (1) / 5.0");
        Console.WriteLine(e.Evaluate());
    }
}
```

**Comment by petli** [comment]
I'm closing this now, but feel free to reopen it if the problem persists even when a new release containing this fix is released.
