### ISSUE TITLE
Some (large) decimals appear to be parsed incorrectly. E.g. "100000000000000.12"

### ISSUE THREAD

**Issue by kierantop** [ncalc/ncalc#335]
**Describe the bug**
In some circumstances decimals appear to be parsed incorrectly. The examples below hint that the problem decreases as the numbers get bigger. I am using version 5.2.8.

**Example Expressions**
``` c#
// 1. 
new Expression("100000000000000.12", ExpressionOptions.NoCache | ExpressionOptions.DecimalAsDefault).Evaluate()
100000000000000           // Expected 100000000000000.12

// 2.
new Expression("100000000000000.12+0.1", ExpressionOptions.NoCache | ExpressionOptions.DecimalAsDefault).Evaluate()
100000000000000.1         // Expected 100000000000000.22

// 3. Using automatic casting from a String
new Expression("\"100000000000000.12\"+0.1", ExpressionOptions.NoCache | ExpressionOptions.DecimalAsDefault).Evaluate()
100000000000000.22        // Correct

// 4.
new Expression("1000000000000000000000.12", ExpressionOptions.NoCache | ExpressionOptions.DecimalAsDefault).Evaluate()
1000000000000000000000.12 // Correct
```

**Comment by gumbarros** [comment]
I don't know if this is expected, but when I removed `ExpressionOptions.DecimalAsDefault` this works:

```cs
    [Fact]
    public void ShouldParseLargeDecimals()
    {
        var expression = new Expression("100000000000000.12+0.1",
            ExpressionOptions.NoCache);

        Assert.Equal(100000000000000.22, expression.Evaluate()); // True
    }
    ```

**Comment by kierantop** [comment]
Removing `DecimalAsDefault` does make that precise example work. However, it leaves me wondering what `DecimalAsDefault` means. The way I'm interpreting it is: "where doubles would usually be used, use decimals instead" - the upshot of which should be that is possible to parse "100000000000000.12" precisely. But that doesn't seem to be the case.

Without the `DecimalAsDefault` flag the following example ends up doing some unexpected rounding:
``` c#
new Expression("100000000000000.12",  ExpressionOptions.NoCache).Evaluate()
100000000000000.13
```
I suspect this is because it's not parsing into a decimal, but a **double** instead:
``` C#
Double.Parse("100000000000000.12")
100000000000000.13
```

Given the following,
``` C#
Decimal.Parse("100000000000000.12")
100000000000000.12
```
I would expect to the following to return 100000000000000.12 but:
``` C#
new Expression("100000000000000.12",  NCalc.ExpressionOptions.DecimalAsDefault | NCalc.ExpressionOptions.NoCache).Evaluate()
100000000000000
```

I might be misunderstanding something though. Thank you for your help!

**Comment by Bykiev** [comment]
According to the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.convert.todecimal?view=net-8.0#system-convert-todecimal(system-double)):

> The [Decimal](https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-8.0) value returned by this method contains a maximum of 15 significant digits. If the value parameter contains more than 15 significant digits, it is rounded using rounding to nearest. The following example illustrates how the [Convert.ToDecimal(Double)](https://learn.microsoft.com/en-us/dotnet/api/system.convert.todecimal?view=net-8.0#system-convert-todecimal(system-double)) method uses rounding to nearest to return a [Decimal](https://learn.microsoft.com/en-us/dotnet/api/system.decimal?view=net-8.0) value with 15 significant digits.

I believe it can be resolved only by BigDecimal implementation in NCalc

**Comment by Bykiev** [comment]
@gumbarros, what do you think about this solution?

```
.Then<LogicalExpression>((ctx, x) =>
{
    long integralValue = x.Item1;
    int zeroCount = x.Item2;
    long? decimalPart = x.Item3;
    long? exponentPart = x.Item4;

    decimal result = integralValue;

    // decimal part?
    if (decimalPart != null && decimalPart.Value != 0)
    {
        var digits = Math.Floor(Math.Log10(decimalPart.Value) + 1) + zeroCount;
        result += (decimal)(decimalPart.Value / Math.Pow(10, digits));
    }

    // exponent part?
    if (exponentPart != null)
    {
        var left = new BigDecimal(result);
        var right = BigDecimal.Pow(10, exponentPart.Value);

        var res = BigDecimal.Multiply(left, right);

        if (res > double.MaxValue)
        {
            if (((LogicalExpressionParserContext)ctx).Options.HasFlag(ExpressionOptions.DecimalAsDefault))
                throw new OverflowException();

            return new ValueExpression(double.PositiveInfinity);
        }
        else if (res < double.MinValue)
        {
            if (((LogicalExpressionParserContext)ctx).Options.HasFlag(ExpressionOptions.DecimalAsDefault))
                throw new OverflowException();

            return new ValueExpression(double.NegativeInfinity);
        }
        else
        {
            if (((LogicalExpressionParserContext)ctx).Options.HasFlag(ExpressionOptions.DecimalAsDefault))
                result = (decimal)res;

            return new ValueExpression((double)res);
        }
    }

    if (((LogicalExpressionParserContext)ctx).Options.HasFlag(ExpressionOptions.DecimalAsDefault))
    {
        return new ValueExpression(result);
    }

    if (decimalPart != null || exponentPart != null)
    {
        return new ValueExpression(Convert.ToDouble(result));
    }

    return new ValueExpression((long)result);
});
```

**Comment by kierantop** [comment]
I've pushed a PR that fixes my scenarios: https://github.com/ncalc/ncalc/pull/340
