### ISSUE TITLE
Error evaluating expression: missing EOF at 'LIKE'

### ISSUE THREAD

**Issue by mgleeson-cdit** [ncalc/ncalc#344]
**Describe the bug**
When attempting to use the LIKE, NOT LIKE, IN operators with strings, I am getting an "EOF" error during Expression evaluation.

Error evaluating expression: missing EOF at 'LIKE' at line 1:6
Error evaluating expression: missing EOF at 'NOT' at line 1:6
Error evaluating expression: missing EOF at 'IN' at line 1:4

**Example Expression**
'Man' LIKE '%M%'
'Man' NOT LIKE '%M%'
'M' IN 'Men are cool'

**Comment by mgleeson-cdit** [comment]
I'm not sure why I used those example expressions, the one in the docs also fails:

'Sergio' IN 'Sergio is at Argentina'  
throws error:
missing EOF at 'IN' at line 1:9

**Comment by gumbarros** [comment]
Docs example is working normally


![image](https://github.com/user-attachments/assets/8c2f07a6-9bac-4dc2-80d1-7ac8f8b27fe3)

Please check if you are in the latest version, `IN` operator was added only at [v5.1.0](https://ncalc.github.io/ncalc/articles/changelog.html#510)

**Comment by mgleeson-cdit** [comment]
Good catch, seems I was using the wrong Nuget package, an extremely old version of NCALC... Upgraded to the latest, but now I'm getting a different error. I understand that I should probably go to StackOverflow now, but in the off-chance there is a simple fix for my issue, I'll just drop the error here... After upgrading, my application now throws this error when attempting to initialize any NCalc class:
The type initializer for 'NCalc.Logging.DefaultLoggerFactory' threw an exception.

**Comment by gumbarros** [comment]
> Good catch, seems I was using the wrong Nuget package, an extremely old version of NCALC... Upgraded to the latest, but now I'm getting a different error. I understand that I should probably go to StackOverflow now, but in the off-chance there is a simple fix for my issue, I'll just drop the error here... After upgrading, my application now throws this error when attempting to initialize any NCalc class: The type initializer for 'NCalc.Logging.DefaultLoggerFactory' threw an exception.

Can you share the stacktrace of the exception?

**Comment by mgleeson-cdit** [comment]
The type initializer for 'NCalc.Logging.DefaultLoggerFactory' threw an exception.
   at NCalc.Cache.LogicalExpressionCache.GetInstance()
   at NCalc.ExpressionBase`1..ctor(TExpressionContext context)
   at NCalc.Expression..ctor(ExpressionContext context)
   at PTP.TableValidator.BuildValidationExpression(ExtractedTableCell cell, ValidationRule rule, List`1 extractedCells)
   at PTP.TableValidator.ValidateCells(String connectionString, List`1 validationRules, List`1 extractedCells)
   at PTP.TableValidator.ValidateAllCells(String connectionString, Int32 extractedTableID)
   at PTP.TableProcessor.UpdateTable(String connectionString, Int32 tableId, String json)

**Comment by gumbarros** [comment]
Never seen this error before, but I would bet on some dependency missing in the log. Are you using the old .NET Framework? Can you try install Microsoft.Extensions.Logging v8.0.0?

**Comment by mgleeson-cdit** [comment]
I don't need logging, anyway to disable this feature?

**Comment by mgleeson-cdit** [comment]
I'm using .NET Framework 4.8
![image](https://github.com/user-attachments/assets/1e6aaec4-09b0-49f1-bc9f-0e07e2d60566)

**Comment by gumbarros** [comment]
> I don't need logging, anyway to disable this feature?

It's disabled by default, but the reference still exists.

**Comment by mgleeson-cdit** [comment]
Okay, I managed to get this working by replacing the existing DLLs in my application with the latest... Last issue, when I try to use Date Expressions now, I'm getting **_Error parsing the expression._**

Expression used: `#2022-08-19# > #2023-01-01#`

**Comment by gumbarros** [comment]
> #2022-08-19# > #2023-01-01#

Dates should be with "/"

![image](https://github.com/user-attachments/assets/eb2fd067-6549-4d4a-9dd7-c68406a90692)

**Comment by mgleeson-cdit** [comment]
Thanks for your help.
