### ISSUE TITLE
How case sensitivity works?

### ISSUE THREAD

**Issue by samanthwal** [ncalc/ncalc#35]
example 1
var calculation = "( [User] == 'ABC') **OR** ([User] == 'XYZ' ) ";

var nCalcExpression = new Expression(calculation, **EvaluateOptions.IgnoreCase)**;

nCalcExpression.Parameters["User"] = "XYZ";

if (nCalcExpression.HasErrors())
{
	**throw new FormatException($"Could not evaluate expression: '{calculation}' due to {nCalcExpression.Error}.");**

//give error here as it does not recognize "OR" but it does "or'
}

Console.WriteLine(nCalcExpression.Evaluate());

example 2
var calculation = "( [User] == 'ABC') or  ([User] == 'XYZ' ) ";

var nCalcExpression = new Expression(calculation, **EvaluateOptions.IgnoreCase)**;

nCalcExpression.Parameters["User"] = **"xyz";**

if (nCalcExpression.HasErrors())
{
	throw new FormatException($"Could not evaluate expression: '{calculation}' due to {nCalcExpression.Error}.");
}

Console.WriteLine(nCalcExpression.Evaluate());

It evaluates to "FALSE" because user value supplied is "xyz" not "XYZ"

then my question is what is the use of EvaluateOptions.IgnoreCase option?

**Comment by petli** [comment]
`EvaluateOptions.IgnoreCase` only affect functions and parameter lookup by making them case insensitve, it has no effect on strings.

If case-insensitive string comparison is desired, a new option property should be added for that so existing behaviour isn't affected.

**Comment by petli** [comment]
This is now fixed in 3.0, you can use any case for keywords like `Or` or `tRuE` etc.
