### ISSUE TITLE
Internal error on trigonometric functions

### ISSUE THREAD

**Issue by ThorstenGroh** [ncalc/ncalc#352]
Since a few weeks I am getting internal error message Everytime I try to evaluate trigonometric functions like sin and cos. Running the same commands in the console mode does however work.

There was no software update, as far as I am aware and I am running the latest version of NCalc+ from the Google Play Store on Android 14 (Google Pixel 7a). The only thing I did, and I am not sure whether this could be related in any way was testing the limits of the factorial function enforcing the first Internal Error ever observed on the app. This test was performed was at around roughly the same time these problems occured.

Since I thought the app might be in some invalid state, I restarted and reinstalled the app multiple times, cleaning the cache and stored data before. Strangely the app remembers the command history after reinstallation. I checked with SD maid 2 if there were any app related files to clean up, but without success.

Is there a way to remove all app related files before reinstallation of the app? Where does NCalc store the data? I searched the whole system folder for *calc* but couldn't find anything, but some file still needs to persist since I still have access to my command history after reinstallation.

Thanks!

**Comment by ThorstenGroh** [comment]
Sorry, I think this is the wrong repo.

**Comment by ThorstenGroh** [comment]
Sorry, I think this is the wrong repo.

**Comment by gumbarros** [comment]
> Sorry, I think this is the wrong repo.

If you are using the package NCalcSync or NCalcAsync this is the right repo. About the question, NCalc don't store any data, but you can remove any NCalc*.dll files to ensure a clean installation.
