### ISSUE TITLE
Case insensitive logical operators 

### ISSUE THREAD

**Issue by huantianad** [ncalc/ncalc#37]
Hey, just dropping in here to ask if it's possible for the `and`, `or`, and `not` operators to be case insensitive, as my current setup already uses `And` and `Or` instead of their lowercase versions.

Ideally custom operators would be nice; however, I understand that that may be unreasonable.

**Comment by petli** [comment]
It is a bit fiddly to support that, since the ANTLR3 grammar that NCalc uses is case-sensitive. There are ways to hack around that, though: https://stackoverflow.com/a/22160240

**Comment by yallie** [comment]
Implemented by @petli in v3.0.
