### ISSUE TITLE
Last version 5.3.1 causes warning: System.Text.Json 9.0.0 doesn't support net6.0

### ISSUE THREAD

**Issue by AntonovAnton** [ncalc/ncalc#379]
Last version 5.3.1 causes warning:

> System.Text.Json 9.0.0 doesn't support net6.0 and has not been tested with it. Consider upgrading your TargetFramework to net8.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.

Please be aware of the potential risks associated with running on earlier versions of the .NET runtime.

**Comment by AntonovAnton** [comment]
.NET 6 is still LTS

**Comment by gumbarros** [comment]
Sorry bro, if it was `net8.0` I would consider a downgrade, but `net6.0` is not supported anymore. I strongly recommend to talk to your employers and do an upgrade.

**Comment by gumbarros** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by AntonovAnton** [comment]
Is it correct? 
![image](https://github.com/user-attachments/assets/823b3321-ed42-4804-95af-87b5d213b4e2)

**Comment by AntonovAnton** [comment]
@gumbarros Thanks! No worries, I just wanted to clarify any potential misunderstanding.

**Comment by gumbarros** [comment]
> Is it correct? ![image](https://private-user-images.githubusercontent.com/943660/397733648-823b3321-ed42-4804-95af-87b5d213b4e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTkxMDcsIm5iZiI6MTczNDY5ODgwNywicGF0aCI6Ii85NDM2NjAvMzk3NzMzNjQ4LTgyM2IzMzIxLWVkNDItNDgwNC05NWFmLTg3YjVkMjEzYjRlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxMjQ2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjNiZGE1ZDA1NWMzZDBiNjhlZGU5ZjgzOWFiZTYwMzkxNTI0ODRjZjE4YWJiMmM0YWIyNzVlZTMzZDU4MzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IU-zRb_H-Cx9XE4Th216GtkoD3iDm_coKZ73Qz66gqI)

Yeah, .NET Framework 4.6.2 is still supported. .NET Standard is like a "contract" between all targets.
