### ISSUE TITLE
Get results of parts of an expression. & odd evaluation results.

### ISSUE THREAD

**Issue by se5a** [ncalc/ncalc#39]
Asking for two things here, I'm trying to debug some funky results in an expression which is using formulas, ie the string expression:
`"Ability('Mass') * 1000000 * TechData('8557acb9-c764-44e7-8ee4-db2c2cebf0bc')"`
This is giving me a funky result when the `"Ability('Mass')` is 8000.  

First off, I want to know if I'm able to break the string expression up and display the results of the functions within the whole expression ie:  
`Ability('Mass') = 8000`     
`TechData('8557acb9-c764-44e7-8ee4-db2c2cebf0bc') = 1`  
I did see taht I could cast the ParsedExpression into a binary expression and see the Left and Right expressions, but that wasn't *quite* what I was after, and didn't seem to see a way to get the evaluated results from that.  can I get something like that as a list?

Second, any ideas on what might be going wrong with the above expression?
![image](https://user-images.githubusercontent.com/1490538/151075766-0f7ef54e-ae9b-44ac-9f54-8f9dc07c6806.png)

![image](https://user-images.githubusercontent.com/1490538/151075800-b064c1a1-ec3c-4542-bf02-154832bf11c5.png)

**Comment by se5a** [comment]
So  yeah, the problem here seems to be integer overflow. 
Mass in this case is a long, the 10000000 could be changed to 1000000.0, but that is really prone to not always happening, and while it makes for an easy quick fix in this particular case, it's not a long term solution. 
tried casting Mass to a double where I thought ncalc would care but that didn't seem to fix the problem. 
Expresson.Options has an OverflowProtection flag, but that didn't seem to make a difference here either.

**Comment by gumbarros** [comment]
@se5a can you share a snippet with a repro of the error? Maybe this is solved at `master`, we allow decimals now with `DecimalAsDefault`

**Comment by gumbarros** [comment]
Closing due inactivity
