### ISSUE TITLE
Implicit Multiplication with parentheses e.g. "60(103/11)" vs "60*(103/11)"

### ISSUE THREAD

**Issue by Kravchenko32** [ncalc/ncalc#44]
![image](https://user-images.githubusercontent.com/37967601/160737468-920cf74c-3e9a-43c9-80dd-3001aa5fd9cd.png)

**Comment by yallie** [comment]
Hello!
NCalc doesn't support implicit multiplication because it supports named parameters and functions.
Expression like this is ambiguous, it's syntactically the same as a function call:

```c#
f(103/11) // is it f * (103 / 11) or f(9.3636...)?
```

**Comment by Kravchenko32** [comment]
Thank you. Sounds like an implementation limitation, which is fine, just unfortunate.
I'll just preprocess input with regex like so [https://dotnetfiddle.net/43AQYw](https://dotnetfiddle.net/43AQYw).
