### ISSUE TITLE
Use this or https://github.com/sklose/NCalc2 ??

### ISSUE THREAD

**Issue by j4cegh** [ncalc/ncalc#49]
I'm wondering which one is better. Thanks!

**Comment by j4cegh** [comment]
> I haven't used NCalc2, sorry.

I have asked some people (including friends) and I have decided to use this. Everyone said this one looked more "professional", and to go with this. So I did. :D

**Comment by petli** [comment]
There's also the sister project https://github.com/ncalc/ncalc-async if you need async symbol and function callbacks. We try to keep the rest the same between the libs.

**Comment by j4cegh** [comment]
> We

I do know that. I've seen it. Thanks!
