### ISSUE TITLE
Nested IF

### ISSUE THREAD

**Issue by ksteh** [ncalc/ncalc#5]
Hi, do NCalc support Nested IF ?

For example, ( 'A' = 'A' ) ? 10 : ( 'B' = 'B' ) ? ' 15 : 20

**Comment by Gillardo** [comment]
I wrote my own function to handle this IIF, and the syntax is slightly different, use it if you want.

Syntax is as such IIF(checkIfTrue, Value, ElseCheckIfTrue, ElseValue, ...... as many times as you want..., LastParameter is valueif none true)

Example.

IIF([A]=true, 1, [B]=true, 2, 3)

So check if A = true, if so return 1, else check if B is true, if so, return 2 else we return 3
```
if (name.ToLower() == "iif")
{
	// loop through the parameters and check if an expression is true, if it is
	// return the result next to the expression, else return the final IF result
	for (var i = 0; i < args.Parameters.Length - 1; i += 2)
	{
		var result = args.Parameters[i].Evaluate();

		if (result != null && (bool)result == true)
		{
			args.Result = args.Parameters[i + 1].Evaluate();
			return;
		}
	}

	// we have got to here because none of the expression resulted in true
	// so we should return the result in the final parameter
	args.Result = args.Parameters.Last().Evaluate();
}
```

**Comment by yallie** [comment]
Looks like `DECODE` in PL/SQL 👍
