### ISSUE TITLE
Package Update

### ISSUE THREAD

**Issue by Shifty15** [ncalc/ncalc#50]
Hi,
 I just want to know if you are planning to release the nuget package. with #46  

Thank you.

Vladimir Jaron

**Comment by Shifty15** [comment]
@yallie Do you have any information?

**Comment by yallie** [comment]
Hello @Shifty15, 

looks like I've missed the github notification for your question, sorry.
Will publish the package today.

**Comment by Shifty15** [comment]
Thank you.
