### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Shifty15** [ncalc/ncalc#51]
Hi,
We updated package and we face performance issue. I created small project with three expression ("Sin(64)", "Sin(80)", "Sin(120)")
and run it in foreach:
 var expressions = new List<string> { "Sin(64)", "Sin(80)", "Sin(120)" };
            foreach (var ex in expressions)
            {
                var expression = new Expression(ex, EvaluateOptions.None);
                expression.Evaluate();
                Task.Delay(5000).Wait();
            }

I used the resharper dotTrace to investigate the performance issue and find one thing.
Different with old version is some TraceEvent you can see it in attached screen.
![image](https://user-images.githubusercontent.com/21225699/170045349-cbaaa7ac-8d69-4547-aad2-ad48f8ccf183.png)

can you check it? We are running quite lot of expression and it slows down our app quite lot.

Thank you.

Vladimir Jaron

**Comment by yallie** [comment]
Hi @Shifty15,

>Task.Delay(5000).Wait();

In your sample code, what's this line for?

---
I don't see any perf differences between versions 3.0 and 3.1:

>D:\Externals\NCalc\NCalcSync\src\NCalc\bin\2>test.exe
>NCalc version: 3.0.0.0
>Elapsed: 00:00:05.0827325
>
>D:\Externals\NCalc\NCalcSync\src\NCalc\bin\3>test.exe
>NCalc version: 3.1.0.0
>Elapsed: 00:00:05.0543491

My benchmark code:

```csharp
using NCalc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

class Program
{
	static void Main()
	{
		Console.WriteLine($"NCalc version: {typeof(Expression).Assembly.GetName().Version}");

		// use different expressions to avoid cache hits
		var expressions = Enumerable.Range(1, 100000).Select(i => $"Sin({i})");

		// warmup
		new Expression("Sin(0)", EvaluateOptions.None).Evaluate();

		// benchmark
		var sw = Stopwatch.StartNew();
		foreach (var ex in expressions)
		{
			var expression = new Expression(ex, EvaluateOptions.None);
			expression.Evaluate();
		}

		sw.Stop();
		Console.WriteLine($"Elapsed: {sw.Elapsed}");
	}
}
```

the only change introduced in this version was [CultureInfo support](https://github.com/ncalc/ncalc/pull/46).
Not sure if it can be responsible for the performance changes, unless it traces something.
NCalc itself doesn't do much tracing except for the expression cache (emits one trace line per expression).

**Comment by Shifty15** [comment]
Oh quite old version 1.3.7.8

**Comment by petli** [comment]
What are the measured times with the older version and the latest? The dottrace screenshot doesn't show that, as far as I can see.

You've underlined `HasErrors` in the screenshot, so a thought about that: Compiled expressions are cached so the compilation part should be insignificant if you evaluate the expressions a lot of times. But if you generate expressions similar to what you showed with different values in the expresison string itself you won't get any benefit from the cache and that expression compilation will end up taking time.

You can solve that by using parameters in your expression, that way the expression is just compiled once and you can evaluate it passing new parameters for each call:
https://github.com/ncalc/ncalc/wiki/Parameters

**Comment by yallie** [comment]
>You can solve that by using parameters in your expression, that way the expression is just compiled once and you can evaluate >it passing new parameters for each call:
>[ncalc/ncalc/wiki/Parameters](https://github.com/ncalc/ncalc/wiki/Parameters)

Totally agree with that.
Reusing compiled expression works orders of magnitude faster. 
Hundred times faster or something like that, depending on how complex is the expression.

>Oh quite old version 1.3.7.8

I haven't found this version, but I see version 1.3.8 published [here](https://www.nuget.org/packages/NCalc).
Still, it doesn't show any perf differences compared to the last release 3.1.0. 
I've modified my benchmark code to demonstrate how faster it's with parameters:

>D:\Externals\NCalc\NCalcSync\src\NCalc\bin\4>test.exe
>NCalc version: 1.3.8.0
>Elapsed (no cache): 00:00:05.1957391
>Elapsed (cached): 00:00:00.0538382
>
>D:\Externals\NCalc\NCalcSync\src\NCalc\bin\3>test.exe
>NCalc version: 3.1.0.0
>Elapsed (no cache): 00:00:05.1358616
>Elapsed (cached): 00:00:00.0472085

Here is the updated benchmark code:

```c#
using NCalc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

class Program
{
	static void Main()
	{
		Console.WriteLine($"NCalc version: {typeof(Expression).Assembly.GetName().Version}");

		// use different expressions to avoid cache hits
		var expressions = Enumerable.Range(1, 100000).Select(i => $"Sin({i})");

		// warmup
		new Expression("Sin(0)", EvaluateOptions.None).Evaluate();

		// benchmark (no cache)
		var sw = Stopwatch.StartNew();
		foreach (var expr in expressions)
		{
			var expression = new Expression(expr, EvaluateOptions.None);
			expression.Evaluate();
		}

		sw.Stop();
		Console.WriteLine($"Elapsed (no cache): {sw.Elapsed}");

		// warmup
		var ex = new Expression("Sin(x)", EvaluateOptions.None);
		ex.Parameters["x"] = 0;
		ex.Evaluate();

		// benchmark (cache compiled expressions)
		sw.Restart();
		foreach (var x in Enumerable.Range(1, 100000))
		{
			ex.Parameters["x"] = x;
			ex.Evaluate();
		}

		sw.Stop();
		Console.WriteLine($"Elapsed (cached): {sw.Elapsed}");
	}
}
```

**Comment by rholek** [comment]
Hi, 

The caching is not something that solves our problem, it was only an example.

I've been doing some investigation on our side and it seems that problem lays in _Trace.TraceInformation_ within method _NCalc.Expression.Compile_. 

I get these results from following test (it's twenty times faster without trace)

![image](https://user-images.githubusercontent.com/6533112/170260968-a3bbb147-4c06-4036-a430-c5eb91043bab.png)

from following test 

```
using System;
using System.Diagnostics;

namespace NCalc.Play
{
    /// <summary>
    /// Summary description for Program.
    /// </summary>
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine($"NCalc version: {typeof(Expression).Assembly.GetName().Version}");

            // use different expressions to avoid cache hits
            const string expressionText = "2 + Sin(15)";


            // warmup
            new Expression(expressionText, EvaluateOptions.None).Evaluate();


            var sw = Stopwatch.StartNew();
            for (int i = 0; i < 100000; i++)
            {
                var expression = new Expression(expressionText, EvaluateOptions.None);
                expression.Evaluate();
            }
            sw.Stop();
            Console.WriteLine($"Elapsed (trace): {sw.Elapsed}");


            Trace.Listeners.Clear();
            

            sw.Restart();
            for (int i = 0; i < 100000; i++)
            {
                var expression = new Expression(expressionText, EvaluateOptions.None);
                expression.Evaluate();
            }
            sw.Stop();
            Console.WriteLine($"Elapsed (without trace): {sw.Elapsed}");

            
        }
    }
}
```


The reason why it works in our version 1.3.7.8 is that it doesn't generate TRACE symbol for Release configuration (while version 3.1.0.0 does).

I'm not sure about proper Trace usage and how should we approach this problem. We could remove trace listeners for our app globally (we don't use Trace at the moment) but it seems more like a hack instead of solution. 

Maybe there should be a parameter that disables the Trace?

**Comment by yallie** [comment]
Hi @rholek, thanks for your help!

>it seems that problem lays in Trace.TraceInformation within method NCalc.Expression.Compile.

That's weird...
Trace is widely used in many libraries as the simplest possible logging.

By default, `Trace.Listeners` contains only `System.Diagnostics.DefaultTraceListener`.
It's very surprising that removing default trace listener fixes this performance issue.
Makes me think that adding `Trace.Listeners.Clear();` line to any application startup code may be a good idea...

>We could remove trace listeners for our app globally (we don't use Trace at the moment) but it seems more like a hack instead of solution.

Agreed! 👍

>Maybe there should be a parameter that disables the Trace?

I don't think that Trace is useful here, so let me just try to disable it for the Release builds.

Looks like TRACE symbol is enabled by default in .NET Standard projects. 
The project file doesn't mention TRACE symbol, but it's still defined:

![image](https://user-images.githubusercontent.com/672878/170338829-f7847e8a-4658-43f5-b8dc-f24ddc7e40a0.png)

Let me try to work around it somehow to undefine TRACE for the Release build.

**Comment by yallie** [comment]
Does anyone know a better way to [undefine TRACE constant for the release build](https://github.com/ncalc/ncalc/commit/158471d5a9dbfbdfbb85df8625e16f3b3dc0699a)? :)

```xml
<!-- TRACE symbol seems to be always defined by default, let's undefine it for the Release builds -->
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants.Replace("TRACE", "NOTRACE"))</DefineConstants>
</PropertyGroup>
```

**Comment by rholek** [comment]
I don't think there is a better way to remove TRACE constant.

Anyway I can confirm that this solves the performance issue. Could you please release it to nuget?

Thanks

**Comment by yallie** [comment]
Sure, no problem
https://www.nuget.org/packages/NCalcSync
