### ISSUE TITLE
Non-breaking space is not recognized as whitespace character 

### ISSUE THREAD

**Issue by rholek** [ncalc/ncalc#56]
Using [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) in formula results in error.

Running
` new Expression("2 * 3").Evaluate();`
results in expression
`Antlr.Runtime.NoViableAltException: 'A recognition error occurred.'`

**Comment by gumbarros** [comment]
I think this is expected behavior from Antlr

**Comment by gumbarros** [comment]
@rholek 

![image](https://github.com/ncalc/ncalc/assets/52143624/df1c2ece-30dc-433d-859c-49808287213b)

Everything work fine without changes at the latest version, can you confirm?

**Comment by gumbarros** [comment]
No feedback and the unit tests are passing.
