### ISSUE TITLE
Subtraction does not work for all numeric types

### ISSUE THREAD

**Issue by baughj** [ncalc/ncalc#58]
Subtraction is not implemented for `byte`. Consider the following program:

```csharp
using System.Diagnostics;
using NCalc;

var expression = "110 - X";

Expression e = new(expression);
e.Parameters["X"] = (byte)50;
var ret = e.Evaluate();
Debug.Assert(ret != null, "Evaluation should not be null");
```

Expected result: 60
Actual result: assertion (evaluation is null)

I believe this is due to https://github.com/ncalc/ncalc/blob/e1d07115914d9d3fb0b6771f1cd3b0fb94621973/src/NCalc/Numbers.cs#L256 never handling the `byte` case, but `sbyte` is handled.
 
Is this intentional (it seems unlikely) or can I submit a PR to fix this?

**Comment by yallie** [comment]
Hello Justin!

I don't think it was intentional.

>can I submit a PR to fix this?

Sure, go ahead! Would be appreciated :)

**Comment by baughj** [comment]
Thanks! I will get something together.

**Comment by baughj** [comment]
https://github.com/ncalc/ncalc/pull/59

**Comment by baughj** [comment]
@yallie what does your normal release schedule / cadence look like?

**Comment by yallie** [comment]
@baughj I've updated the nuget package:

https://www.nuget.org/packages/NCalcSync/3.6.0

Sorry for the delay.
Thanks for your contribution! :)

**Comment by baughj** [comment]
Thanks very much!
