### ISSUE TITLE
When .Net Core Version ?

### ISSUE THREAD

**Issue by mtugnoli** [ncalc/ncalc#7]
Hi,
I like very much this library !
Do you think to make it a version for .net core?

**Comment by yallie** [comment]
Hi @mtugnoli ,

I've updated the dependencies and added .NET Standard 2.0 target to the project.
Looks like everything builds fine at [Appveyor](https://ci.appveyor.com/project/yallie/ncalc).
Release build of NCalc.dll gets merged with Antlr3 runtime to produce single assembly.
