### ISSUE TITLE
Swedish characters in parameters

### ISSUE THREAD

**Issue by garagenisse** [ncalc/ncalc#70]
Hi, i get this exception when using swedish characters in parameters:

mismatched input 'avgift' expecting ')' at line 1:15
extraneous input ')' expecting EOF at line 1:23

My example is:

string exp = "2*avgift+(miljöavgift+4)";
Expression e = new Expression(exp);
e.Parameters["avgift"] = 5;
e.Parameters["miljöavgift"] = 1;
var v = e.Evaluate();

I have tried various things with unicode but the only thing that works for me is replace'ing "åäö" and that is not an option, any directions of how i can get this to work? I i put parameters in square brackets it seems to work fine, however that is not doable either.

Regards Andreas

**Comment by ThomasHambach** [comment]
This is likely due to the ANTLR4 grammar not being set up for Unicode characters. I will have a look at the grammar file and get back to you.

**Comment by garagenisse** [comment]
Hi, have you had the time to look in to this matter?

Regards Andreas

**Comment by Bykiev** [comment]
You should use a square brackets with parameters like this

`string exp = "2*[avgift]+([miljöavgift]+4)";`
