### ISSUE TITLE
Calculating Expressions With Null Objects

### ISSUE THREAD

**Issue by Beckdotan** [ncalc/ncalc#72]
Hi, I want to calc expressions like "X + 5"  OR "X * 5 "where X is double?[] and I use EvaluateOptions.IterateParameters. 
so sometimes, X[i] ==  null and this creates an error since it seems that ncalc doesn't know what to do with null objects when calculates? 

Can I override it? Can I decide for example that for summing null will be like 0 and for multiplication of null and something will always be null? 

Thanks

**Comment by KreativJos** [comment]
Overriding doesn't seem to be possible, built-in functions have precedence on the EvaluateFunction event.
My workaround is to use try from [NCalcExtensions](https://github.com/panoramicdata/PanoramicData.NCalcExtensions/tree/main)

**Comment by Beckdotan** [comment]
thanks for the tip. 

As far as I can realize, there is still a problem since I want to act differently according to the operand. so, for every sum I want to replace null with 0 and sum, and for every Mult action I want to return null if one of the objects is null. 

Do you have any solution to this problem?

**Comment by yallie** [comment]
Hi @Beckdotan,

I'm afraid you'll need to write a custom evaluation visitor.
Something like this:

```csharp
public class MyVisitor : EvaluationVisitor
{
	public MyVisitor(EvaluateOptions options = EvaluateOptions.IgnoreCase, CultureInfo cultureInfo = null) :
		base(options, cultureInfo ?? CultureInfo.CurrentCulture)
	{
		CultureInfo = cultureInfo;
		Parameters = new Dictionary<string, object>();
	}
	
	private CultureInfo CultureInfo { get; set; }
	
	public override void Visit(BinaryExpression expression)
	{
		var myOperations = new[]
		{
			BinaryExpressionType.Plus,
			BinaryExpressionType.Minus, 
			BinaryExpressionType.Times,
			BinaryExpressionType.Div,
			BinaryExpressionType.Modulo,
		};
		
		if (!myOperations.Contains(expression.Type))
		{
			base.Visit(expression);
			return;
		}
		
		expression.LeftExpression.Accept(this);
		var left = Result;

		expression.RightExpression.Accept(this);
		var right = Result;
		
		switch (expression.Type)
		{
			case BinaryExpressionType.Plus:
				Result = Numbers.Add(left ?? 0d, right ?? 0d, CultureInfo);
				break;
				
			case BinaryExpressionType.Minus:
				Result = Numbers.Subtract(left ?? 0d, right ?? 0d, CultureInfo);
				break;

			case BinaryExpressionType.Times:
				Result = (left == null || right == null) ? null :
					Numbers.Multiply(left, right, CultureInfo);
				break;
				
			case BinaryExpressionType.Div:
				Result = (left == null || right == null) ? null :
					Numbers.Divide(Convert.ToDouble(left, CultureInfo), right, CultureInfo);
				break;
				
			case BinaryExpressionType.Modulo:
				Result = (left == null || right == null) ? null :
					Numbers.Modulo(left, right, CultureInfo);
				break;
		}
	}
}
```

**Comment by yallie** [comment]
Here is the full sample code: https://dotnetfiddle.net/oydjKt

**Comment by Beckdotan** [comment]
> Here is the full sample code: https://dotnetfiddle.net/oydjKt

thank you so much! this is really useful!
I will be Implementing it in the next day or 2 and if I will have few more questions I will write it down here :) 

Thanks again!

**Comment by yallie** [comment]
You're welcome! :)
