### ISSUE TITLE
Floating point number cannot be parsed and throws an exception if floating point number does not have a fractional part

### ISSUE THREAD

**Issue by Kizuto3** [ncalc/ncalc#73]
Hello, I am trying to evaluate an expression like "1. + 2", but "1." argument cannot be parsed. I checked the documentation and noticed that NCalc supports floating point numbers in format "1.1" and ".1". Is it possible for it to support floating point numbers in format "1." where there is no fractional part?

**Comment by yallie** [comment]
Hello @Kizuto3, sorry for my late reply. 

Which version of ncalc are you using?
The last version should support numbers ending with decimal point, like "1.",  there is a [unit test for that](https://github.com/ncalc/ncalc/blob/a775494490fa6052de8b9ae130f9a7a45a630af8/test/NCalc.Tests/Fixtures.cs#L53C17-L53C17):

```csharp
[TestMethod]
public void ShouldParseValues()
{
  ...
  Assert.AreEqual(123d, new Expression("123.").Evaluate()); // trailing decimal point
  Assert.AreEqual(12300d, new Expression("123.E2").Evaluate()); // no fractional part after decimal point
}
```
