### ISSUE TITLE
# is comments?

### ISSUE THREAD

**Issue by ShadAhm** [ncalc/ncalc#74]
Hi Ncalc,

We have found that the token `#` seems to mean comments in your library.

E.g: `1+2+3+4+5#hello world`evaluates to 15

However, we couldn't find any documentation about this feature. We are afraid to continue using it in case it gets removed someday and all our saved expressions are screwed.

Could you please confirm if `#` is indeed intended for comments and if it's safe to use it in our expressions?

Thank you!

**Comment by petli** [comment]
Sorry, there's no comment feature in NCalc. `#` is used to express `DateTime`, e.g. as `#2023-06-08T09:56#` (or anything else you can get `DateTime.Parse()` to interpret).

That expression should not evaluate at all but result in a syntax error, so you have found a bug in the parser. Which version of the library are you using?

**Comment by ShadAhm** [comment]
@petli I am using `<PackageReference Include="CoreCLR-NCalc" Version="2.2.113" />`

**Comment by ShadAhm** [comment]
Aha, ok sorry. Then I guess it's not a problem with your repo. 

Thanks for the help anyway, appreciate the quick response! :)
