### ISSUE TITLE
Nuget package version

### ISSUE THREAD

**Issue by ThomasHambach** [ncalc/ncalc#75]
Hi again! It looks like there hasn't been a release in a long time. Do you think we can get a new NuGet package built with the latest changes?

Additionally, I'd be happy to help maintain this package. I see NcalcAsync does get new package versions.

**Comment by yallie** [comment]
Hi Thomas!

Sorry for my late reply. 
You're right, I haven't published the nuget release in a while, let me fix that.
The publishing process is automated, but it's not yet documented.

I would be glad to add you as nuget package owner.
Please let me know what's your user name at nuget.org.

**Comment by yallie** [comment]
https://www.nuget.org/packages/NCalcSync/3.7.0

**Comment by ThomasHambach** [comment]
Awesome, thanks!
