### ISSUE TITLE
CompareUsingMostPreciseType chooses first option, not best

### ISSUE THREAD

**Issue by ThomasHambach** [ncalc/ncalc#76]
Not sure if we can consider it a bug, but we're seeing some difficulty with `CompareUsingMostPreciseType`. Specifically, if the expression is written in the form of `myparam > 0 AND myparam < 2`. The value of `myparam` here is 2.4564.

This works, until serializing the expression for performance. I am assuming the data type gets lost. That ends up entering the `CompareUsingMostPreciseType` with the values for a being: 2 and for b being: 2.4. This results in the type being considered an int64, and the comparison using that type as well. So for `2.4` we will satisfy the need of it to be a `2`.

Is there any reason why currently the CommonTypes are in the order of Int64, Double, Boolean, String, Decimal? Additionally, would it make sense to have the types compared rather than picking the first one? 

https://github.com/ncalc/ncalc/blob/master/src/NCalc/Domain/EvaluationVisitor.cs#L48

**Comment by yallie** [comment]
>Is there any reason why currently the CommonTypes are in the order of Int64, Double, Boolean, String, Decimal?

I'm not sure why the types are in that order. Looks like bug to me.

**Comment by ThomasHambach** [comment]
Ok, I made #78 for this and will close this issue.
