### ISSUE TITLE
Replacement for old functions in NCalc v1.3.8

### ISSUE THREAD

**Issue by attiqeurrehman** [ncalc/ncalc#77]
Hi,

We have a legacy application using NCalc v1.3.8 and are now upgrading it to the latest version. However, we noticed that the following functions are no longer supported:

- Pos
- Int
- Fix
- Rand

Are there any replacements for these functions? Additionally, can we add custom functions in NCalc?

We would appreciate any help you can provide.

**Comment by attiqeurrehman** [comment]
Thanks for the quick reply. From what I can see it is from Sébastien Ros.

![Untitled](https://github.com/ncalc/ncalc/assets/1382615/e6aed38f-e9d9-451c-af80-144dc10b4982)

Anyways will submit the PR for the above-mentioned functions.

**Comment by yallie** [comment]
I think that all forks keep the original copyright by Sébastien Ros to comply the license.

**Comment by attiqeurrehman** [comment]
Yeah, that would make sense.
