### ISSUE TITLE
Is there a way to override operators?

### ISSUE THREAD

**Issue by Kizuto3** [ncalc/ncalc#79]
Is it possible to programmatically override operator '&' to perform concatenation? If it is, how can I achieve it?

**Comment by yallie** [comment]
Hi @Kizuto3,

There is no built-in operator overloading feature.
But I believe it's possible using custom EvaluationVisitor descendant.

Something like that (pseudocode):

```csharp
public class ConcatenationVisitor : EvaluationVisitor
{
  ...
  public override void Visit(BinaryExpression expression)
  {
    if (expression.Type == BinaryExpressionType.BitwiseAnd)
    {
      if (left() is string l && right() is string r)
      {
        Result = l + r;
        return;
      }
    }

    base.Visit(expression);
  }
}
```

and use the visitor to evaluate the expression:

```csharp
var visitor = new ConcatenationVisitor(Options, CultureInfo);
expression.Accept(visitor);
Console.WriteLine($"Result = {visitor.Result}");
```

**Comment by Kizuto3** [comment]
Hi @yallie , thanks for your response!
EvaluationVisitor.Result`s setter is private, I cannot access it in a derived class. Can its setter be made protected in the next release? I am using the nuget package and want to keep it that way to keep up with the updates. And I would prefer to no use reflection to access EvaluationVisitor.Result`s setter.
![image](https://github.com/ncalc/ncalc/assets/38604580/0acbe0a1-5420-4e8e-94f9-84dc67912042)

Thank you!

**Comment by yallie** [comment]
Oh, good point! Yes, Result setter should be protected.

**Comment by yallie** [comment]
https://www.nuget.org/packages/NCalcSync/3.8.0

**Comment by Kizuto3** [comment]
Thank you so much!
