### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Yeah69** [ncalc/ncalc#8]
Does a nuget package exist for this fork? Or will there be one?

**Comment by yallie** [comment]
Hello @Yeah69,

the Nuget package for this fork doesn't exist yet.
I was planning to port the library to the latest Antlr3 runtime with .NET Core support first.

**Comment by ntimmerman** [comment]
I would also find this useful.

**Comment by thirdprize** [comment]
and me

**Comment by yallie** [comment]
Hi everyone, 

apologies for my late reply.
Here is the Nuget package: nuget.org/packages/NCalcSync

Regards, Alex
