### ISSUE TITLE
3.6.0 version much faster than 3.7.0 and 3.8.0 in Xamarin Forms

### ISSUE THREAD

**Issue by Jones-Abramoff** [ncalc/ncalc#81]
Hi, please check why 3.6.0 is much faster than the recent versions.

I'm using Visual Studio 2022 17.7.0 in a Xamarin Forms Android project using expressions like this:
"0=1&&2=1&&0=1||0=1&&2=2&&0=1||0=1&&2=3&&0=1||0=1&&2=4&&0=1||0=1&&2=5&&0=1||0=1&&2=6&&0=1||0=1&&2=7&&0=1||0=1&&2=8&&0=1||0=1&&2=9&&0=1||0=1&&2=10&&0=1||0=1&&2=11&&0=1||0=1&&2=12&&0=1||0=1&&2=1&&0=2||0=1&&2=2&&0=2||0=1&&2=3&&0=2||0=1&&2=4&&0=2||0=1&&2=5&&0=2||0=1&&2=6&&0=2||0=1&&2=7&&0=2||0=1&&2=8&&0=2||0=1&&2=9&&0=2||0=1&&2=10&&0=2||0=1&&2=11&&0=2||0=1&&2=12&&0=2||0=1&&2=1&&0=3||0=1&&2=2&&0=3||0=1&&2=3&&0=3||0=1&&2=4&&0=3||0=1&&2=5&&0=3||0=1&&2=6&&0=3||0=1&&2=7&&0=3||0=1&&2=8&&0=3||0=1&&2=9&&0=3||0=1&&2=10&&0=3||0=1&&2=11&&0=3||0=1&&2=12&&0=3||0=1&&2=1&&0=4||0=1&&2=2&&0=4||0=1&&2=3&&0=4||0=1&&2=4&&0=4||0=1&&2=5&&0=4||0=1&&2=6&&0=4||0=1&&2=7&&0=4||0=1&&2=8&&0=4||0=1&&2=9&&0=4||0=1&&2=10&&0=4||0=1&&2=11&&0=4||0=1&&2=12&&0=4||0=1&&2=1&&0=5||0=1&&2=2&&0=5||0=1&&2=3&&0=5||0=1&&2=4&&0=5||0=1&&2=5&&0=5||0=1&&2=6&&0=5||0=1&&2=7&&0=5||0=1&&2=8&&0=5||0=1&&2=9&&0=5||0=1&&2=10&&0=5||0=1&&2=11&&0=5||0=1&&2=12&&0=5||0=1&&2=1&&0=6||0=1&&2=2&&0=6||0=1&&2=3&&0=6||0=1&&2=4&&0=6||0=1&&2=5&&0=6||0=1&&2=6&&0=6||0=1&&2=7&&0=6||0=1&&2=8&&0=6||0=1&&2=9&&0=6||0=1&&2=10&&0=6||0=1&&2=11&&0=6||0=1&&2=12&&0=6"

I tried downloading the NCalc 3.8.0 source code and running it.

The Windows app was fast as expected.

The Xamarin was too slow.

I believe the difference is due to the ANTLR library change.

Best regards,

Jones Abramoff

**Comment by Jones-Abramoff** [comment]
3.9.0 is also much slower than 3.6.0

**Comment by yallie** [comment]
Hi @Jones-Abramoff, sorry to hear about that!

>The Windows app was fast as expected.
>The Xamarin was too slow.
>I believe the difference is due to the ANTLR library change.

Sounds likely... Perhaps one of the upcoming ANTLR version will address this issue.

**Comment by Jones-Abramoff** [comment]
Please let me know when a new ANTLR version is included in this project.
It's currently using version 4.12 and there is 4.13.1.
Thanks.

**Comment by yallie** [comment]
@Jones-Abramoff,

I've updated the ANTLR runtime to the latest version v4.13.1.
Feel free to reopen the issue if it doesn't help.
