### ISSUE TITLE
Decimal number multiplication doesn't working everytime

### ISSUE THREAD

**Issue by Teyfik-Eren-Erez** [ncalc/ncalc#84]
Hi, 
I tried a simple decimal number multiplication. While I was expecting a 3.6 result, program calculated 3,5999999999999996. 
This problem only occurs at multiples of 3 and three. How can i solve this problem without using round function? 

> var e= new Expression("1.2 * 3");

> Debug.Assert(3.6 == e.Evaluate());

**Comment by Glavyanov** [comment]
Hi,
In this simple decimal multiplication try =>

```
  Debug.Assert(3.6M == Convert.ToDecimal(e.Evaluate()));

```

**Comment by Teyfik-Eren-Erez** [comment]
Hi @Glavyanov, 
Thank you for your suggestion. I can use this until the bug is fixed.

**Comment by cliff-pennalligen** [comment]
It is not a bug.  Please see this explanation: https://truth.dev/floating_point.html

**Comment by gumbarros** [comment]
Try using `EvaluateOptions.DecimalAsDefault`, if everything is alright, we can close the issue.

**Comment by Teyfik-Eren-Erez** [comment]
I get this result in linux. If I tried in windows, everyting is ok. I will use windows server. So I can close this issue. 
Thanks for helping.
