### ISSUE TITLE
Question on Invariant Case String Comparasion

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc#85]
Hey! First of all congrats on the project!

I'm planning to use use it at [JJMasterData](https://www.github.com/JJConsulting/JJMasterData). 

Currently we compile expressions using `DataTable.Compute`, but I would like to migrate to NCalc.

To migrate without breaking changes, imagine the following expression:

```
'List' = 'LIST'
```

`DataTable.Compute` returns `true`, but NCalc returns `false`. Is there a way to do invariant case String Comparasion?

**Comment by yallie** [comment]
Hello @gumbarros, see my answer here: https://github.com/ncalc/ncalc-async/issues/24

TL/DR: no built-in support, but can be implemented using custom evaluation visitor.
