### ISSUE TITLE
Binary operations 'And' and 'Or' do not support "And(x, y)" or "Or(x, y)" syntax

### ISSUE THREAD

**Issue by Kizuto3** [ncalc/ncalc#87]
I've noticed that 'And' and 'Or' binary operators have a specific syntax like "x And y" and "x Or y". However, I would like to use them as functions (so they can have syntax like "And(x, y)"). When I try to evaluate such expression, the EvaluationException is thrown with "extraneous input 'And' expecting {'+', '-', '!', '~', '(', TRUE, FALSE, NOT, ID, INTEGER, FLOAT, STRING, DATETIME, NAME} at 1:1
mismatched input ',' expecting ')' at 1:6" Error. 
Is there a way to parse them as functions or at least raise EvaluateFunction event when the compiler encounters such syntax?

**Comment by yallie** [comment]
Hi @Kizuto3,

NCalc treats `AND` and `OR` as reserved words.
To use them as identifiers, you can escape them with square brackets, similar to TransactSQL language: `[and]`, `[or]`.
To handle custom functions, add an event handler like this:

```csharp
var exp = new Expression("[and](a, b)", EvaluateOptions.None);
exp.Parameters["a"] = true;
exp.Parameters["b"] = false;
exp.EvaluateFunction += EvalFunction;

Console.WriteLine("Result = {0}", exp.Evaluate());

// custom function evaluator
static void EvalFunction(string name, FunctionArgs args)
{
	// assume arbitrary number of arguments
	if (name == "and")
	{
		var result = true;
		foreach (var p in args.Parameters)
		{
			result = result && Convert.ToBoolean(p.Evaluate());
			if (!result)
			{
				break; // short circuit boolean expression
			}
		}
		
		args.Result = result;
	}
}
```

Here is the working example: https://dotnetfiddle.net/TCR2ER

**Comment by Kizuto3** [comment]
Hello @yallie 
Thanks for the quick reply! This workaround can solve my issue. Thank you!
