### ISSUE TITLE
Expression should take have a constructor that takes in an EvaluationVisitor

### ISSUE THREAD

**Issue by thetreatment** [ncalc/ncalc#89]
https://github.com/ncalc/ncalc/blob/9f28e7b31ddfe42f8cd74128acb0bddc5511046f/src/NCalc/Expression.cs#L243

If you have a custom EvaluationVisitor class,  you cannot use Expression.Evaluate because the visitor is local to the method. That means you need to also virtually re-implement the entire Expression class

**Comment by gumbarros** [comment]
Good morning @thetreatment . Do PR #90 fix your issue?

**Comment by thetreatment** [comment]
yes, that looks good!
Thanks

**Comment by thetreatment** [comment]
PR hasn't been merged yet; and I added some addition comments on PR regarding some extra changes to make EvaluationVisitor sub-classable.
