### ISSUE TITLE
Is it possible to add Async support to Expression#Evaluate method?

### ISSUE THREAD

**Issue by anhhnguyen206** [ncalc/ncalc#9]
Hi there,

One of my custom expressions will be making a call to a database.  Right now I have to do Task.Wait() on my call instead of using async/await.  Is it possible to add support for async/await in case we want to perform some custom expressions that requires making network/database calls?

Maybe we should not alter the behavior of the Evaluate() method but rather add a new method call EvaluateAsync()?

**Comment by theadin** [comment]
I've also been trying to find a solution for this.

**Comment by yallie** [comment]
I'm afraid there is no easy way to make ncalc async-aware, sorry.
Please feel free to reopen if you have a prototype solution and want to create a pull request.

**Comment by petli** [comment]
I've added an async interface to NCalc-NetCore:
https://github.com/Alterdata/NCalc-NetCore/pull/1

I could retarget it to this project, if it's interesting. (The reason I sent it there instead is that those are the only published .NET Core-compatible packages of NCalc). 

There is some potential for breaking changes, as detailed in the PR.

**Comment by yallie** [comment]
Hi @petli,

I'm very impressed!

>I could retarget it to this project, if it's interesting.

That would definitely be great!
But it looks like quite a lot of work, isn't it?

>There is some potential for breaking changes, as detailed in the PR.

That's probably OK for such a big new feature...
Or we can create a separate repository/nuget for the async version.
I'll add you to the ncalc organization if you're interested.

But I'm not sure about bridging the [synchronous and asynchronous versions of Evaluate](https://github.com/Alterdata/NCalc-NetCore/pull/1/files#diff-928e9c69741d6c28ffaf26fb644c7c99R231).
Accessing Task.Result may result in a [deadlock in certain conditions](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).
You may want to add ConfigureAwait(false) to avoid deadlocks.

**Comment by petli** [comment]
I'm also a bit worried about bridging the sync/async versions. `ConfigureAwait(false)` seems dangerous too, if the `EvaluateFunction` or `EvaluateParameter` event handlers expect to execute on the UI thread. 

So either rewriting this to have an `AsyncExpression` and `AsyncEvaluationVisitor` with base classes for code that can be shared with the old sync implementations, or splitting into a new ncalc-async library.

Would the async stuff work while still targeting .NET Framework 3.5? If not, I guess it must be a new library unless projects needing supporting such an old version are referred to https://github.com/pitermarx/NCalc-Edge

What is the plan for this ncalc repo, in terms of targeting net-standard and publishing on nuget?

**Comment by yallie** [comment]
>ConfigureAwait(false) seems dangerous too, if the EvaluateFunction or EvaluateParameter event handlers expect to execute on the UI thread.

Good point!

>So either rewriting this to have an AsyncExpression and AsyncEvaluationVisitor with base classes for code that can be shared with the old sync implementations, or splitting into a new ncalc-async library.

Splitting into a new ncalc-async library looks preferable to me.

>What is the plan for this ncalc repo, in terms of targeting only net-standard and publishing on nuget?

This repository exists because the [official fork of ncalc](https://github.com/sheetsync/NCalc) is not maintained since 2012, and we needed to track bugfixes made to ncalc used in our internal projects. I didn't publish any nuget packages from this repo.

If we split into ncalc-async project (and a new nuget package), the backwards compatibility wouldn't be an issue. The new library will target .NET Core and .NET Fx4+ and just leave out all the synchronous code.

**Comment by petli** [comment]
Well, then this seems like a good home for an ncalc-async targeting net-standard. Since I want nuget packages I guess I have to ensure there are some, too 🙂

**Comment by petli** [comment]
I've retargeted my async code on top of this code base and pushed it to https://github.com/ncalc/ncalc-async now. Next I'll look at getting CI and package publishing running, but I reckon this issue can now be closed as resolved 🙂

**Comment by anhhnguyen206** [comment]
Awesome work guys! Thanks for seeing this through!

**Comment by petli** [comment]
Now there's a nuget package published too: https://www.nuget.org/packages/NCalcAsync/

**Comment by yallie** [comment]
That's great Peter!
Thanks for your effort!

**Comment by petli** [comment]
Well, I needed this myself too :)

I've set up an Azure Pipeline project to build and publish packages for ncalc-async. Drop me a line (my email address is in my public profile) if you want access to it to be able to publish new packages, @yallie

**Comment by theadin** [comment]
I'll be checking this out next week 👍

**Comment by theadin** [comment]
I also want to thank you Peter. I'm now using this in a big project and having the async built-in is great.
