### ISSUE TITLE
(0+0)>0 is true???

### ISSUE THREAD

**Issue by scottbarnesbass** [ncalc/ncalc#99]
My test is failing, I've been debugging for hours now. Can anyone shed any light on this please?

```
        var selectionAlgorithm = "(TAX_Y+TAX_YW)>0";    
    
        var e = new Expression(selectionAlgorithm);
        e.AddParameter("TAX_Y", "0");
        e.AddParameter("TAX_YW", "0");

        Assert.False((bool)e.Evaluate());
```

**Comment by yallie** [comment]
Hi @scottbarnesbass,

you're probably comparing strings.

`TAX_Y` = "0", `TAX_YW` = "0", so `TAX_Y+TAX_YW` = "00".

Then `"00" > 0` expression type is detected as String.
So `"00" > "0"` is evaluated as `Comparer.Compare("00", "0") > 0`.

Try specifying your parameters as numbers, i.e. replace "0" with 0.

Cheers, Alex

**Comment by scottbarnesbass** [comment]
Thank you so much @yallie. Saved the day!

**Comment by yallie** [comment]
You're welcome! :)
